### ISSUE TITLE
Running ghorg a second time to clone from gitlab asks for password

### ISSUE THREAD

**Issue by jeffrson** [gabrie30/ghorg#116]
**Describe the bug**

I'd like to backup all projects I can access from gitlab (gitlab.com).

With ghorg I need to clone all groups seperately - it this correct? Or is there any way to clone really all groups that the token gives access to? (yes, this is somewhat unrelated question...)

`ghorg clone <group>` works fine. Now when I want to update the backup it asks for user password a couple of times. I guess that's one for each concurrency access.

On a further unrelated question: would this be the correct way to keep up-to-date backups? If "backup" is done via "--mirror" will it be kept up-to-date with `git remote update`?

I tried with backup setting in config.yaml as well as without - same behaviour.

I'm not sure what further information you need to reproduce the problem, so please ask.

**Expected behavior**

Should update cloned or mirrored repository.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux

**Comment by gabrie30** [comment]
Correct, currently you can only clone one group at a time. However It should be possible to clone all groups with some adjustments. I'm not sure I'll have time for this at the moment unfortunately. However it could be a good feature for someone if they wanted to tackle it.

If you want to do a backup you can use the `--backup` flag in ghorg and it will clone with the `--mirror` flag https://github.com/gabrie30/ghorg/blob/master/cmd/clone.go#L429 there is some documentation on the mirror flag [here](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---mirror) So it will fetch all remote branches and will be updated with `git remote update`. I'm sure there are a few different ways, but this way seems reasonable to me, but If there is something wrong with the approach please share.

Running ghorg a second time should not ask you for a password. Sounds related with how credentials are setup locally or a bug I have yet to figure out. Have you tried cloning using `--protocol=ssh` flag?

**Comment by jeffrson** [comment]
> Correct, currently you can only clone one group at a time. However It should be possible to clone all groups with some adjustments. I'm not sure I'll have time for this at the moment unfortunately. However it could be a good feature for someone if they wanted to tackle it.

I'd check it out - unfortunately I'm not yet a golang programmer :-(

> If you want to do a backup you can use the `--backup` flag in ghorg and it will clone with the `--mirror` flag https://github.com/gabrie30/ghorg/blob/master/cmd/clone.go#L429 there is some documentation on the mirror flag [here](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---mirror) So it will fetch all remote branches and will be updated with `git remote update`. I'm sure there are a few different ways, but this way seems reasonable to me, but If there is something wrong with the approach please share.

Sounds perfect to me - in fact I did it as such myself, but for every single repository. Now there are just too many of them.

Unfortunately I couldn't really use it so far because of the password:
 
> Running ghorg a second time should not ask you for a password. Sounds related with how credentials are setup locally or a bug I have yet to figure out. Have you tried cloning using `--protocol=ssh` flag?

I created a token and put it into "GHORG_GITLAB_TOKEN". This worked with https for the first run, then asks for password when retrying. It seems, however, that `--protocol=ssh` does the job. Great!!!

Just to be sure - the command for initial backup and every other update is always "clone" - right?

Thanks a lot!

**Comment by gabrie30** [comment]
Awesome! Ya not sure why that error occurs, I think something like [this](https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe) could allow you to use https, but might not be worth it if ssh is working

If the repo is already cloned it will perform a glt remote update, since you cannot clone a repo twice, [heres](https://stackoverflow.com/questions/17712468/what-is-the-difference-between-git-remote-update-git-fetch-and-git-pull#:~:text=git%20remote%20update%20will%20update,not%20merge%20any%20changes%20in.&text=git%20pull%20will%20update%20and,to%20update%20a%20local%20branch.) some more info on that

**Comment by methadata** [comment]
I was getting password prompt, not matter if it was first clone or not. Even using `--protocol ssh`.

Also, I faced generic errors (error 128, 401) related with authZ in Gitlab.

Following the link you provided, I was able to fix it by configuring git globally:

```bash
git config --global url."git@gitlab.mydomain.com:".insteadOf http://gitlab.mydomain.com/
git config --global url."git://".insteadOf https://
```

Thanks!!

**Comment by gabrie30** [comment]
> I was getting password prompt, not matter if it was first clone or not. Even using `--protocol ssh`.
> 
> Also, I faced generic errors (error 128, 401) related with authZ in Gitlab.
> 
> Following the link you provided, I was able to fix it by configuring git globally:
> 
> ```shell
> git config --global url."git@gitlab.mydomain.com:".insteadOf http://gitlab.mydomain.com/
> git config --global url."git://".insteadOf https://
> ```

Thank you for confirming this worked @methadata! I will add this to the readme.

**Comment by gabrie30** [comment]
Going to close this issue. Thanks for the great feedback everyone!

**Comment by jeffrson** [comment]
Well, I had to look into this problem again.

AFAICT, it's the `git remote update` call that asks for the password. This is because the remote origin is set to URL without token (https://gitlab.com/...) after cloning the mirror.

Possible solution: set origin to CloneUrl before `git remote update`. Of course, this could leave the credential inside the .git folder when ghorg would be stopped during the operation. OTOH, this would happen during the initial clone as well.
