### ISSUE TITLE
"go get github.com/gabrie30/ghorg" installs old ghorg (v1.0.7)

### ISSUE THREAD

**Issue by bj4rtmar** [gabrie30/ghorg#121]
I'm not sure if this is a bug or not but I want to describe the problem I had when installing ghorg with go v1.16 and how I got around it, in case it'll help others.

For the record, my `go env` is:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/bjartmar/.cache/go-build"
GOENV="/home/bjartmar/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bjartmar/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bjartmar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1774404658=/tmp/go-build -gno-record-gcc-switches"
```

When installing ghorg via `go get github.com/gabrie30/ghorg`
It installs an old version (v1.0.7) of ghorg:
```
go: downloading github.com/gabrie30/ghorg v1.0.7
<snip>
```

But when i do:
`GO111MODULE=auto go get github.com/gabrie30/ghorg`
or 
`GO111MODULE=off go get github.com/gabrie30/ghorg`
it installs the expected version (v1.5.1 as of this writing)

So it seems to me "go get" fails to install ghorg when in module-aware mode.

**Comment by gabrie30** [comment]
Thanks for raising this issue @bj4rtmar

Seems like in go 1.16 `go install` [should be used](https://www.pixelstech.net/article/1608961684-About-go-get-and-go-install-in-Go-1-16) instead of `go build` for binaries

I'll update the readme to suggest

`go install github.com/gabrie30/ghorg@1.5.0`

**Comment by gabrie30** [comment]
@bj4rtmar just learned why this was happening. Go modules requires the git tag to start with v to pick it up. I had used v.1.0.7 but then dropped the v in the tags which is why it wasn't picking up the latest releases.
