### ISSUE TITLE
GL: v4 API support.

### ISSUE THREAD

**Issue by jtagcat** [gabrie30/ghorg#123]
**Describe the bug**
GitLab: 410 {error: API V3 is no longer supported. Use API V4 instead.}

**Comment by gabrie30** [comment]
@jtagcat can you provide a little bit more context around the error. Where are you seeing it, what commands are you running, what does does your ghorg.conf look like.

The gitlab library should be using the v4 api https://github.com/xanzy/go-gitlab

**Comment by jtagcat** [comment]
While attempting to use the v3, the mentioned response is returned.
When using v4, splashscreen is printed, yet there's no output nor any changes in the output directory.

I did a quick script myself, so I'm not very keen on debugging more for now.

**Comment by gabrie30** [comment]
Seems like a reasonable error message if your gitlab instance is out of date, will close.
