### ISSUE TITLE
Branch option not working

### ISSUE THREAD

**Issue by dword-design** [gabrie30/ghorg#128]
**Describe the bug**
When I use the branch option (e.g. directly via the CLI), always the default branch is checked out, not the specified one.

**To Reproduce**
1. `ghorg clone --branch renovate/lock-file-maintenance`
2. The default branch is checked out instead of `renovate/lock-file-maintenance`

**Expected behavior**
The branch `renovate/lock-file-maintenance` is checked out.

**Notes**
Interestingly the console output shows that it is checking out the specified branch but it isn't happening.

```
Success cloning repo: git@github.com:foo/bar.git -> branch: renovate/lock-file-maintenance
...
```

**Comment by gabrie30** [comment]
Thanks for raising this @dword-design, does it check out the branch on the second run?

**Comment by dword-design** [comment]
@gabrie30 hmm the branch is gone now, hard to test.

**Comment by gabrie30** [comment]
This should only be a problem for the inital clone. Subsequent runs will checkout the specified branch. This PR will fix the initial clone issue tho. https://github.com/gabrie30/ghorg/pull/129

**Comment by dword-design** [comment]
@gabrie30 It doesn't fix it though if the branch is passed via `--branch`. Also, I was thinking what the expected behavior is if the branch does not exist: Should the default branch be checked out or should the repo not be cloned at all? From a use case point of view I'd vote for not cloning it at all, otherwise there is some invalid state there.
