### ISSUE TITLE
Pass cookie to allow for easy two factor authentication.

### ISSUE THREAD

**Issue by verbruggenalex** [gabrie30/ghorg#130]
**Is your feature request related to a problem? Please describe.**
I can not reach my companies Gitlab instance because it is behind 2FA.

**Describe the solution you'd like**
Easiest solution for me would be to pass a cookie in my ghorg command. I'm not familiar with go, but possibly there is an option to pass a cookie to the client. This would make ghorg a usable solution for me.

**Describe alternatives you've considered**
Just doing my own manual curl with -b option to set my cookies. And looping over my own results with my own script...

**Comment by gabrie30** [comment]
You should be able to use ghorg to clone your repos even if gitlab is behind 2fa given your personal access token has the correct scopes. Have you followed the [gitlab](https://github.com/gabrie30/ghorg#gitlab-setup) section in the readme, if so what kind of behavior are you seeing?
