### ISSUE TITLE
How to config cloning from a list of orgs, gitlab and github

### ISSUE THREAD

**Issue by TriplEight** [gabrie30/ghorg#131]
I have several orgas in github and on-prem gitlab, is there a way to config the setup ghorg or writing a script would be a solution here?
Thanks.

**Comment by gabrie30** [comment]
It can only clone a single org at a time so using it in a script would be your best bet.

**Comment by TriplEight** [comment]
yeah, thanks, that's what I did.
Just a suggestion that it should be easy to implement with yaml configs that for each org/user one can create another block with the same variables, name it as an org name and call it with a flag in CLI.

**Comment by gabrie30** [comment]
Yea thats not a bad idea
