### ISSUE TITLE
Support --match-suffix to filter repos

### ISSUE THREAD

**Issue by petomalina** [gabrie30/ghorg#136]
As a user, I want to clone repositories with certain suffixes. We use suffixes to distinguish the environment (e.g. prod, dev, stage) and I'd like to only mass-clone one of those environments.

**Is your feature request related to a problem? Please describe.**
When doing mass repo changes, I want to clone repos with certain suffixes, make changes, commit, push, and remove them. This is only for bulk operations. I can't do that without the --match-suffix.

**Describe the solution you'd like**
I'd like to see a `--match-suffix` or something like `--match-regex` in the options of `ghorg clone`.

**Describe alternatives you've considered**
Filtering in the IDE based on the folder pathname. OK, but still clones tons of repos I don't really need.

**Additional context**
We use these env repos for infra-related work, where IaaC is applied. We use Gitlab.

**Comment by gabrie30** [comment]
@petomalina `--match-regex` is on master if you want to give it a try will close this but will reopen if you run into issues

**Comment by petomalina** [comment]
@gabrie30 thanks so much!
