### ISSUE TITLE
Config ignored with latest changes (1.7.0, @master)

### ISSUE THREAD

**Issue by petomalina** [gabrie30/ghorg#140]
**Describe the bug**
After recently updating ghorg, my conf.yaml seems to be completely ignored.

Error I am getting:
```
$ ghorg clone <path>

Could not find a valid github token. GHORG_GITHUB_TOKEN or (--token, -t) flag must be set. Create a personal access token, then set it in your $HOME/.config/ghorg/conf.yaml or use the (--token, -t) flag, see 'GitHub Setup' in README.md
```

My general configuration looks like this:
```
# Change SCM base url, for on self hosted instances (for gitlab, use format of https://git.mydomain.co$
# default: uses github/gitlab public api
# flag (--base-url)
GHORG_SCM_BASE_URL: https://gitlab.<org>.com

# Which provider to clone from (github, gitlab, gitea or bitbucket)
# default: github
# flag (--scm, -s)
GHORG_SCM_TYPE: gitlab

# How you'd like to clone the repos (https or ssh)
# default: https
# flag (--protocol)
GHORG_CLONE_PROTOCOL: ssh
```

**To Reproduce**
1. `go install github.com/gabrie30/ghorg@master` 
2. run ghorg clone

**Expected behavior**
Ghorg should pick up the Gitlab configuration as in previous versions

**Additional context**
I believe this is broken from the recent update, as the update with --match-regex worked just fine

After running `go install github.com/gabrie30/ghorg@4b402f2e44bc9d0e697fb37e29794b13aa576230`, everything works just fine, so this is broken only for the latest 2 commits.

**Comment by gabrie30** [comment]
Thanks for reporting this @petomalina! A fix should be on master.
