### ISSUE TITLE
Keep changes in already existing clones

### ISSUE THREAD

**Issue by harmathy** [gabrie30/ghorg#153]
**Is your feature request related to a problem? Please describe.**

If some clones already exist, local changes are overwritten.

**Describe the solution you'd like**

There should be at least an option to not touch already existing repositories.

**Describe alternatives you've considered**

The best solution for my use case would be to clone repositories, which do not exist locally, and do a `git fetch` for already existing repositories.

**Additional context**

I work on a large amount of repositories. New repositories are created from time to time in our organization. It would be nice if I could use ghorg to keep my set of local clones up-to-date, without loosing local changes.

**Comment by gabrie30** [comment]
@harmathy Fix will be on master shortly, let me know how it goes. Make sure version is v1.7.2 locally then run `ghorg clone kubernetes --no-clean`

**Comment by gabrie30** [comment]
Going to close this out, can reopen if you have issues.

**Comment by harmathy** [comment]
Wow, that was quick🤩 I just tested `master` and it works like a charm. Thank you!

**Comment by gabrie30** [comment]
Thanks for the update @harmathy! Glad its working and thanks for the suggestion.
