### ISSUE TITLE
SSH protocol stopped working with Gitlab

### ISSUE THREAD

**Issue by obvionaoe** [gabrie30/ghorg#157]
**Describe the bug**
SSH no longer works for cloning gitlab repos, only HTTPS
when trying to use SSH I get `Error: exit status 128`

**To Reproduce**
Use SSH as the protocol

**Expected behaviour**
it should work with SSH

**Desktop (please complete the following information):**
 - OS: Alpine Linux
 - ghorg Version: 1.7.1

**Comment by gabrie30** [comment]
Thanks for raising this @obvionaoe 

Wasn't able to replicate this locally. Few things to try

1. has your ssh key changed at all? are the permissions on the file correct? can you successfully perform a `git clone git@github.com:somerepo.git` on the machine?
2. has the alpine image you are using did it recently get updated? does ghorg work on an older version of the image?

If these don't work can you share with me the command you are running?

**Comment by obvionaoe** [comment]
where does ghorg expect the ssh key to be?

**Comment by gabrie30** [comment]
> where does ghorg expect the ssh key to be? that might be the issue

ghorg knows nothing about your ssh keys, it uses git which should have all that configuration...can you check if you can do a normal git clone using the ssh clone url? eg. `git clone git@gitlab.com:somerepo.git`

**Comment by obvionaoe** [comment]
I did not take that into consideration, that was the problem, I was missing my ssh config.
Thanks
