### ISSUE TITLE
Cannot clone subgroups

### ISSUE THREAD

**Issue by softbless1** [gabrie30/ghorg#159]
refer to issue #88  i tried the latest version, this issue is still there 

i'm using this command : 
`ghorg clone all-groups --base-url=http://code.xyz.com --scm=gitlab --token=abc123 --preserve-dir --insecure-gitlab-client --output-dir=/root/backup`

the error message saying : 
Encountered an error, aborting
error fetching repos for group 'chopstick', error: group 'chopstick' does not exist

note : chopstick is a subgroup and has 2 repositories

**Comment by avelino** [comment]
I am having the same problem using version 1.47.0

**Comment by gabrie30** [comment]
Thanks @avelino are you having issues with `ghorg clone all-groups` specifically?

It looks like from their [changelog](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/CHANGELOG.md) the api calls ghorg uses were introduced in 13.0.1+ `Groups API has top_level_only option to exclude subgroups`

I'll wait for you to confirm before updating the README.md

**Comment by avelino** [comment]
> Thanks @avelino are you having issues with ghorg clone all-groups specifically?


```
ghorg clone all-groups --base-url=http://gitlab.xxx.xxx.xxx/ --scm=gitlab --token=xxx
gitlab.xxx.xxx.xxx

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : gitlab
* Type          : org
* Protocol      : https
* Location      : /Users/thiago.avelino/ghorg/
* Concurrency   : 25
* Base URL      : http://gitlab.xxx.xxx.xxx/
* Config Used   : /Users/thiago.avelino/.config/ghorg/conf.yaml
*************************************

fetching repos for group: aeon-manager
Encountered an error, aborting
error fetching repos for group 'aeon-manager', error: group 'aeon-manager' does not exist
```

**Comment by gabrie30** [comment]
Thanks @avelino I've update the readme and examples to note the version requirements.

**Comment by stxpons** [comment]
> Thanks @avelino I've update the readme and examples to note the version requirements. Cloning groups/subgroups individually should still work for you. Can re-open if thats not the case.

I think maybe you should use /groups/${groupId}/projects instead of /groups/${groupName}/projects.
I had tested on our gitlab server, when use ${groupName}, it will cause 404 error while the group is a subgroup[like parentGroup/subGroup].
