### ISSUE TITLE
New valid GitLab tokens fail config validation

### ISSUE THREAD

**Issue by vegas1880** [gabrie30/ghorg#160]
**Describe the bug**
New GitLab tokens contain a "glpat-" prefix, adding 6 bytes to the 20 bytes token.
The bug is in this line: https://github.com/gabrie30/ghorg/blob/f50372890c4285008fddd6c2f684c311da976d72/configs/configs.go#L217
It compares with 20, while it should be 20 for legacy tokens and 26 for new tokens.
I changed it locally to 26 and it works with the new tokens.

For more info see here:
https://gitlab.com/gitlab-org/gitlab/-/issues/342327

**To Reproduce**
Create a new GitLab token and try to use it either with -t or in the config file.

**Expected behavior**
New GitLab tokens should be valid

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS 64 bit

**Comment by gabrie30** [comment]
Thanks @vegas1880 will get a fix for this in today

**Comment by gabrie30** [comment]
Fix is now on master, thanks again

**Comment by vegas1880** [comment]
Thanks for fixing it.
v1.7.3 fixed the issue for the -t command line but not for the config file parsing. This line is now the problem:

https://github.com/gabrie30/ghorg/blob/e6cf8a29b919f28f0a41be9790d6a6b41f58ac93/configs/configs.go#L171

You can merge the logic maybe, or add logic to support glpat- to this line as well.
