### ISSUE TITLE
New valid GitLab tokens fail config file validation

### ISSUE THREAD

**Issue by vegas1880** [gabrie30/ghorg#162]
New GitLab tokens contain a "glpat-" prefix, adding 6 bytes to the 20 bytes token.
It compares with 20, while it should be 20 for legacy tokens and 26 for new tokens.
I changed it locally to 26 and it works with the new tokens.

For more info see here:
https://gitlab.com/gitlab-org/gitlab/-/issues/342327

v1.7.3 fixed the issue for the -t command line but not for the config file parsing. This line is now the problem:
https://github.com/gabrie30/ghorg/blob/e6cf8a29b919f28f0a41be9790d6a6b41f58ac93/configs/configs.go#L171

You can merge the logic maybe, or add logic to support glpat- to this line as well.

**Comment by gabrie30** [comment]
Thanks again @vegas1880! Fix should be on master.
