### ISSUE TITLE
Documentation fix for GitLab requiring Username/Password

### ISSUE THREAD

**Issue by vegas1880** [gabrie30/ghorg#163]
The first "Known issue" in the docs is about a username requirement when using GitLab. I just had this problem on Ubuntu 20.04 LTS 64bit, and I suggest the following explanation:
1. Make sure that you can clone using SSH with no username/password using "git clone git@gitlab.com:xxx/yyy/zzz.git" (replace the link to the correct git file). If you can't clone or it requires a password, fix this problem first (unrelated to ghorg)
2. In "git config", make sure that the email is correct
3. Delete all files and folders (git repos) in the ghorg directory
4. Run ghorg once again using -t (the gitlab personal access token, new tokens start with "glpat-"), --scm=gitlab --protocol=ssh

**Comment by gabrie30** [comment]
Awesome thanks!
