### ISSUE TITLE
Support BitBucket Personal Access Tokens

### ISSUE THREAD

**Issue by skupjoe** [gabrie30/ghorg#171]
Currently, ghorg only supports app passwords for BitBucket.

For our infrastructure, I can only use SSH/PAT

Please consider supporting access tokens for BitBucket. I ultimately needed to use https://github.com/bric3/bitbucket-project-synchronizer to sync our project repos.

**Comment by gabrie30** [comment]
Is this what you need? https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html

**Comment by skupjoe** [comment]
I believe so. In the latest release it looks like it is called HTTP Access Tokens, but however in my version it is called PAT:
https://confluence.atlassian.com/bitbucketserver072/personal-access-tokens-1005335924.html

**Comment by gabrie30** [comment]
@skupjoe I opened a pull request above, hopefully this will work. I wasn't able to test it however due to not having access to a data center server nor getting it to run locally. If you have a chance can you test it out? That would be very useful. Let me know if you need assistance.

**Comment by gabrie30** [comment]
Went ahead and merged this. Let me know if you get a chance to test it.
