### ISSUE TITLE
Cannot access self-hosted GitLab instances with a custom PAT prefix

### ISSUE THREAD

**Issue by dschafhauser** [gabrie30/ghorg#175]
**Describe the bug**
Access to self-hosted GitLab instances with a custom PAT prefix doesn't work.

With GitLab 14.5, a default prefix `glpat-` has been introduced. Support for this has been implemented in https://github.com/gabrie30/ghorg/issues/160 and https://github.com/gabrie30/ghorg/issues/162.

However, it is still possible for the administrator of a self-hosted GitLab instance to define a custom PAT prefix as described in the [GitLab documentation](https://docs.gitlab.com/ee/user/admin_area/settings/account_and_limit_settings.html#personal-access-token-prefix).

**To Reproduce**
Create a new GitLab token with custom prefix which is non-empty and unequal to `glpat-`.
Try to use it either with `-t|--token` or in the config file.

**Expected behavior**
Accessing via GitLab tokens with an arbitrary custom prefix should work.

**Possible solutions**
The token validation logic either accepts no prefix, or only `glpat-`:
https://github.com/gabrie30/ghorg/blob/d1f0be388f2aa81fbe7253f94cb307c33ae7a6fe/configs/configs.go#L229

Two ideas:
* Remove or loosen the length check of PATs to only check a minimum length
* Introduce `GHORG_GITLAB_TOKEN_PREFIX` to define it consciously

**Comment by gabrie30** [comment]
Thank you @dschafhauser for such a detailed issue! I think we can be less strict about checking the tokens.

**Comment by gabrie30** [comment]
@dschafhauser the fix is on master i'll cut a release later today or this weekend, thanks again!
