### ISSUE TITLE
Clone doesn't work on Windows if `GHORG_SCM_BASE_URL` is used

### ISSUE THREAD

**Issue by dschafhauser** [gabrie30/ghorg#177]
Thank you for the amazingly fast fix of https://github.com/gabrie30/ghorg/issues/175! I've found another small issue 😊

**Describe the bug**
Cloning repos using a custom `GHORG_SCM_BASE_URL` on Windows doesn't work because all API URL calls are appended with `\`.
Defining the Base URL via `--base-url=https://my.instance.com` works though.

Config.yaml:
```yaml
GHORG_SCM_BASE_URL: https://my.instance.com/
```

Looking at the output of `ghorg`, the Base URL is appended with `\`:
```cmd
PS D:\repos\gh\ghorg> .\ghorg.exe clone org --dry-run
...
* Base URL      : https://my.instance.com/\
...
Encountered an error, aborting
error fetching repos for group 'org', error: group 'org' does not exist
```

It's not just a display issue, but all API calls are appended with `\`:
```
https://my.instance.com/%5C/api/v4/groups/org/projects?include_subgroups=true&page=1&per_page=100
```

**To Reproduce**
Set `GHORG_SCM_BASE_URL` to a custom URL and attempt to clone on a Windows machine.

**Expected behavior**
It works on Windows 😄

**Cause**
Both, local drive paths _and_ URL paths are sanitized using the OS-specific separators:
https://github.com/gabrie30/ghorg/blob/d7f79c86fe8c13872f9cc9b202b847888cfa0e12/cmd/root.go#L112-L114
https://github.com/gabrie30/ghorg/blob/d7f79c86fe8c13872f9cc9b202b847888cfa0e12/configs/configs.go#L71-L79
https://github.com/gabrie30/ghorg/blob/d7f79c86fe8c13872f9cc9b202b847888cfa0e12/configs/configs.go#L82-L90

**Comment by gabrie30** [comment]
Thanks for raising another thoughtful issue @dschafhauser! The fix should now be on master let me know if its not working as expected.
