### ISSUE TITLE
Allow negative filtering (exclude matching repos instead of including them)

### ISSUE THREAD

**Issue by dschafhauser** [gabrie30/ghorg#179]
**Is your feature request related to a problem? Please describe.**
I'm working with a larger org with many projects. Many are relevant, but a lot are just 'playground' or 'demo' projects which I'd like to **exclude** from the clone process.

ghorg supports **including** projects if they match a certain prefix (`--match-prefix`) or regex (`--match-regex`), but **excluding** doesn't work as easily.

Using the `--match-regex` option, I've tried a negative lookahead, but the standard regex library for go [doesn't seem to support it](https://groups.google.com/g/golang-nuts/c/7qgSDWPIh_E).

```
$ ./ghorg.exe clone org --dry-run --match-regex '^(?!.*playground).*$'
...
* Regex Match   : ^(?!.*playground).*$
...

Filtering repos down by regex that match the provided...

panic: regexp: Compile(`^(?!.*playground).*$`): error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

One could still do it with some other ["trickery"](https://stackoverflow.com/questions/466053/regex-matching-by-exclusion-without-look-ahead-is-it-possible), but this is definitely no ad-hoc CLI fun anymore 😅

**Describe the solution you'd like**
Some ideas:

* additional CLI options for _exclude_ matching:
	* Example: `--exclude-match-prefix` and `--exclude-match-regex`
	* It's debatable if mixing the existing _include_ and new _exclude_ options would be useful, and what the rules for that would be
* additional CLI option for inverting the matching logic (the 'grep' way)
	* Example: `-v, --invert-match`
	* Would probably make sense that it applies to both, `--match-prefix` and `--match-regex`
	* Mixing _include_ and _exclude_ is not possible
	* One might even argue if this would apply to `--topics`, too
* use a (non-standard) regex library which supports negative lookahead
	* [`regexp2`](https://github.com/dlclark/regexp2) could be a choice
	* However, even with negative lookahead, negative matching is still a bit awkward

**Describe alternatives you've considered**
Probably just live with the extra cloned repos.
Doing it via topics would require a persistent change within every repo in the org (and isn't supported for GitLab by ghorg at the moment, see https://github.com/gabrie30/ghorg/issues/180). Creating a positive inclusion regex would be quiet long and requires maintenance.

Let me know your thoughts, and if you would appreciate some help! 😄

**Comment by gabrie30** [comment]
Good point! I thinking the `--exclude-match-prefix` and `--exclude-match-regex` would be the best option. The `--invert-match` could get confusing for users to know which flags they can invert.

For the `--exclude-match-prefix` we would just add something similar to this here https://github.com/gabrie30/ghorg/blob/master/scm/github.go#L173-L185

And the `--exclude-match-regex` just add another if block here https://github.com/gabrie30/ghorg/blob/master/cmd/clone.go#L330-L334

I think if we just add those two blocks having both `--include-match-regex` and `--exclude-match-regex` or any combination wouldn't cause any issues.

Ya the golang regex engine is a bit lacking. However I do like that its in the stdlib tho. Do you have any thoughts on it? I'm open to trying a new engine.

I always appreciate some help. Feel free to help support this feature if you have the time. I won't start working this issue or https://github.com/gabrie30/ghorg/issues/180 until I know you aren't going to work on it.

**Comment by gabrie30** [comment]
@dschafhauser This feature is now on master if you want to test it out.
