### ISSUE TITLE
Add support for filtering by topics via `--topics` for GitLab

### ISSUE THREAD

**Issue by dschafhauser** [gabrie30/ghorg#180]
**Is your feature request related to a problem? Please describe.**
Filtering according to topics is already supported for GitHub and Gitea via CLI option `--topics`.
Currently, this is not available for GitLab however.

**Describe the solution you'd like**
I don't have experience with the 'topic' feature of GitHub/Gitea, but GitLab does also have the concepts of Topics, which seems quiet similar to me. See [topics API](https://docs.gitlab.com/ee/api/topics.html) and [project API](https://docs.gitlab.com/ee/api/projects.html).

If (equivalent) support for GitLab isn't feasible, I suggest to at least throw a warning/error when using `--topics` if `GHORG_SCM_TYPE` is `gitlab`. Currently, the option is just ignored.

Let me know your thoughts, and if you would appreciate some help! 👍

**Comment by gabrie30** [comment]
Great idea! I wasn't even aware GitLab had topics thanks for pointing it out! 

I always appreciate some help. Feel free to help support this feature if you have the time. I won't start working this issue or https://github.com/gabrie30/ghorg/issues/179 until I know you aren't going to work on it.

**Comment by gabrie30** [comment]
@dschafhauser This feature is now on master if you want to test it out.
