### ISSUE TITLE
Can't clone a private bitbucket organization

### ISSUE THREAD

**Issue by Riduidel** [gabrie30/ghorg#185]
**Describe the bug**
I've used ghorg to clone a Github organization, and it worked very well.
Now I try to clone the content of a private bitbucket organization, and it fails with a 404.
Unfortunatly, I can't make the org name public.

I'm running the following command

```
C:\Users\nicolas-delsaux\Documents\Décathlon\Outdoor>ghorg.exe clone --scm bitbucket https://bitbucket.org/my_very_private_org/

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : bitbucket
* Type          : org
* Protocol      : https
* Location      : C:\Users\nicolas-delsaux\ghorg\
* Concurrency   : 25
* Config Used   : C:\Users\nicolas-delsaux\.config\ghorg\conf.yaml
*************************************

Encountered an error, aborting
404 Not Found
```

**Expected behavior**
I would have liked to have all repos cloned

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.7.8

**Comment by gabrie30** [comment]
Thanks @Riduidel I'll try to take a look at this over the weekend. I don't have access to a private bitbucket org so we'll see how far I can get.
