### ISSUE TITLE
exported GHORG_CONFIG environment variable is not picked up by ghorg

### ISSUE THREAD

**Issue by Rabattkarte** [gabrie30/ghorg#187]
**Describe the bug**
I want to point ghorg to a configuration file via the exported environment variable `GHORG_CONFIG`. I am using a self-hosted GitLab configuration. My setup is as follows:

```sh
$ env | grep GHORG_CONFIG
GHORG_CONFIG=/Users/my_user/workspace/CUSTOMERS/my_customer/ghorg.yaml
$ pwd
/Users/my_user/workspace/CUSTOMERS/my_customer
$ ls
ghorg.yaml
$ ghorg clone some-group
Could not find a valid github token. GHORG_GITHUB_TOKEN or (--token, -t) flag must be set. Create a personal access token, then set it in your $HOME/.config/ghorg/conf.yaml or use the (--token, -t) flag, see 'GitHub Setup' in README.md
```

My config in `/Users/my_user/workspace/CUSTOMERS/my_customer/ghorg.yaml` is as follows:

```yaml
---
GHORG_ABSOLUTE_PATH_TO_CLONE_TO: /Users/my_user/workspace/CUSTOMERS/my_customer/ghorg
GHORG_BACKUP: false
GHORG_BITBUCKET_APP_PASSWORD:
GHORG_BITBUCKET_OAUTH_TOKEN:
GHORG_BITBUCKET_USERNAME:
GHORG_BRANCH:
GHORG_CLONE_PROTOCOL: ssh
GHORG_CLONE_TYPE: org
GHORG_CLONE_WIKI: true
GHORG_COLOR: enabled
GHORG_CONCURRENCY: 5
GHORG_DRY_RUN: false
GHORG_EXCLUDE_MATCH_REGEX:
GHORG_FETCH_ALL: true
GHORG_GITEA_TOKEN:
GHORG_GITHUB_TOKEN:
GHORG_GITLAB_TOKEN: MY_GITLAB_TOKEN
GHORG_INSECURE_GITLAB_CLIENT:
GHORG_MATCH_PREFIX:
GHORG_MATCH_PREFIX:
GHORG_MATCH_REGEX:
GHORG_NO_CLEAN: true
GHORG_OUTPUT_DIR:
GHORG_PRESERVE_DIRECTORY_STRUCTURE: true
GHORG_SCM_BASE_URL: https://gitlab.my-tld.com/
GHORG_SCM_TYPE: gitlab
GHORG_SKIP_ARCHIVED: false
GHORG_SKIP_FORKS: false
GHORG_TOPICS:
```

**Expected behavior**
I want ghorg to use the configuration that I have configured in `GHORG_CONFIG`. This is not happening.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.2 (20G314)
 - ghorg version: v1.7.9
 - zsh version: zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by Rabattkarte** [comment]
My workaround is a wrapper script right now:

```
#!/usr/bin/env bash

# path to ghorg binary
GHORG=$(brew --prefix)/bin/ghorg

command $GHORG --config="$GHORG_CONF" "$@"
```

**Comment by Rabattkarte** [comment]
I believe one problem is that the example config uses `GHORG_CONFIG` whereas in the go code only `GHORG_CONF` is used. Please notice the missing `IG` in `CONFIG`.

Exporting `GHORG_CONF` still does not work, though.

I guess the offending code is here: https://github.com/gabrie30/ghorg/blob/0cee3ccd9d92214f613866d12ae7784dafc7cf5e/cmd/root.go#L128-L137

I believe in both cases of this condition, you are not respecting the environment variable?

**Comment by gabrie30** [comment]
Thanks for finding that! Going to merge some changes to master if you have go setup locally would you be able to test?

**Comment by Rabattkarte** [comment]
Compiled, but sorry, your PR did not fix the bug itself. I still believe that the logic in that condition above is wrong.

You are never checking if GHORG_CONFIG is set and therefore never use it.

I believe you are only checking if a flag `--config` was passed. In all other cases, you are falling back to `configs.DefaultConfFile()`. I'm not that good with Go, but I give a PR draft a try.

**Comment by Rabattkarte** [comment]
I created https://github.com/gabrie30/ghorg/pull/189

**Comment by gabrie30** [comment]
Thanks again for all your help @Rabattkarte!
