### ISSUE TITLE
Exclude GitLab groups by regex

### ISSUE THREAD

**Issue by schelhorn** [gabrie30/ghorg#191]
Thanks for making `ghorg` - it's awesome!

It would be great of we could get a feature to exclude GitLab *groups* from being cloned, using a command similar to the include/exclude syntax for individual repos.

Assuming that I have a GitLab group "testing_mygroup" with an individual project/repo "repo_1" inside it, I propose a new command to `ghorg clone`, such as `--exclude-group-match-regex` so that I could do `--exclude-group-match-regex "testing_*"` so that neither the group directory is made in my output dir (assuming that I have used `--preserve-dir `), nor "repo_1" is cloned.

Thanks again!

**Comment by gabrie30** [comment]
@schelhorn new feature is on master if you want to give it a try
