### ISSUE TITLE
SaaS Gitlab keep asking for password

### ISSUE THREAD

**Issue by Savemech** [gabrie30/ghorg#199]
Hi there! Thanks for awesome tool that helped a lot!
For some reasons it is stopped working with gitlab
**Describe the bug**
Cannot clone repositories, because gitlab somehow asking for username and password
**To Reproduce**
I guess find some bulky gitlab org to clone from
try to clone
there we go

**Expected behavior**
its suppose to working just fine

```
#:~:1> ghorg version
v1.7.11
#:~:0> ghorg clone --token <CUT> orgname --scm gitlab --concurrency 1

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 TIME TO GHORG
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : gitlab
* Type          : org
* Protocol      : https
* Location      : /root/ghorg/
* Concurrency   : 1
* Config Used   : none
*************************************

191 repos found in orgname

Username for 'https://gitlab.com': ^C
```

**Additional context**
token scope:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/8943498/158553306-26bde1ad-ba93-4cfe-ae22-b7825e026aa3.png">
but actually with even all checkboxes ticked it is not working :C

**Comment by gabrie30** [comment]
Can you try https://github.com/gabrie30/ghorg#known-issues

**Comment by gabrie30** [comment]
Closing as issue should be resolved by following the troubleshooting section above
