### ISSUE TITLE
GHORG_ABSOLUTE_PATH_TO_CLONE_TO dir is created with incorrect perms

### ISSUE THREAD

**Issue by clarson99** [gabrie30/ghorg#20]
when the GHORG_ABSOLUTE_PATH_TO_CLONE_TO dir does not yet exist, ghorg creates it with these perms: 

`drw-r--r--    2 curt  staff         64 May 26 19:40 ghorg`

I think the safest thing to do is create the dir with 700 and let the user update it later if they deem it safe to do so.

**Comment by gabrie30** [comment]
Changed from 666 to 700 https://github.com/gabrie30/ghorg/pull/21
