### ISSUE TITLE
Not all repository cloned for use mode

### ISSUE THREAD

**Issue by iDoka** [gabrie30/ghorg#200]
### Describe the bug
When I clone my personal account the ghorg view only public repos (not private).
Meanwhile in org mode `--clone-type=org` ghorg works very well with both pub+priv repos.

### To Reproduce
`ghorg clone iDoka --scm=github --clone-type=user`

```
*************************************
* SCM           : github
* Type          : user
* Protocol      : https
* Location      : /home/doka/github.backup/
* Concurrency   : 25
* Config Used   : /home/doka/.config/ghorg/conf.yaml
*************************************
42 repos found in iDoka
```

The same issue with usage ssh protocol: 
`ghorg clone iDoka  --scm=github --clone-type=user --protocol=ssh`

```
*************************************
* SCM           : github
* Type          : user
* Protocol      : ssh
* Location      : /home/doka/github.backup/
* Concurrency   : 25
* Config Used   : /home/doka/.config/ghorg/conf.yaml
*************************************
42 repos found in iDoka
```

### Expected behavior
I expect that clone all repos in user mode: both public and private

**Desktop (please complete the following information):**
 - OS: CentOS 7 x86_64
 - CLI

**Comment by iDoka** [comment]
Just in case my `personal access token` settings:
![Screenshot from 2022-04-15 20-45-29](https://user-images.githubusercontent.com/4820969/163603918-07d1d9b6-058c-4130-8812-baa9d9c4e072.png)

**Comment by gabrie30** [comment]
Thanks @iDoka the fix should be in the latest release
