### ISSUE TITLE
Add `--prune` flag to remove archived or deleted repos from local store

### ISSUE THREAD

**Issue by toothbrush** [gabrie30/ghorg#205]
I searched the docs for such a feature, and searched the issues, but i don't think this exists.  My apologies if i missed it.

Context: my team has archived a few repos, and renamed another repo from `a` to `b`.  It'd be nice if my `~/ghorg` folder could be kept up to date so that after a clone, i don't have both `org/a` and `org/b` there.  Same for the archived repos.

Feature request: it'd be nice if there were a `--delete` flag like `rsync` has, to also remove repos that don't exist in the source org any more.

**Comment by gabrie30** [comment]
Thanks for the feature request! You're correct it does not exist. I've considered something like this before, however wasn't too keen on deleting directories. My thinking was that users could always delete the ghorg dir and re-clone everything if things were really out of sync or they wanted to start fresh.

That being said, if there is such a feature, I'd probably want to make each deletion require a manual confirmation from the user. So the process would look like 

1. clone using the --delete flag
2. clone finishes
3. user is prompted about each repo that exists locally but not in the remote, asking user if they would like to delete the repo
4. user responds with yes or no then is asked about the next repo
5. this repeats until finished

**Comment by toothbrush** [comment]
My organisation is large enough that it takes at least an hour or two to make a fresh clone on our office internet connection, so while that's a reasonable workaround, with our fairly frequent repo-archiving (and as such, me not wanting to find code search results in repos that aren't relevant any more), it'd be great to have something smarter!

I agree with your suggestion to do it in two phases, do the "upsert" / additive clone as usual, with an optional "remove deleted" phase after if the user opts in with `--delete`.  Then, i'd suggest a `--no-confirm-delete` flag for people like me who like living on the edge 😉 

I can see if i get a chance to spike something out at some point.

**Comment by toothbrush** [comment]
Last night i hacked together a thing that works perfectly for me.  I'll try polish the branch a bit.

I can add the `y/n` prompt you describe, but to be honest, as a user of a CLI tool such as `ghorg`, i would not expect interactive input.  I think showing the proposed actions in `ghorg clone --prune --dry-run` (already implemented) and having the prune feature be off by default is enough for me as a user, but obviously i'll defer to your taste if you're willing to consider my PR 🙂 

If i added a `y/n` prompt before each deletion, i'd also add a `--do-not-prompt-interactively-when-pruning` (with a better name of course) so that folks with my preference can have their way, too 😄

**Comment by toothbrush** [comment]
Alright, i've polished my PR a bit.  I've tried to match the existing coding style.  Let me know if you think it's up to scratch!

**Comment by toothbrush** [comment]
I see you've already cut a release @gabrie30 – thank you so much for the quick turnaround! ✨
