### ISSUE TITLE
Prune should not rely on plain repo Name and folder name

### ISSUE THREAD

**Issue by i3v** [gabrie30/ghorg#210]
**Describe the bug**
As a follow-up for #207, I've noticed few more issues with `sliceContainsNamedRepo(cloneTargets, f.Name())` [here](https://github.com/gabrie30/ghorg/blob/ed0955c9dd09b77329bfc4cece4fb97501cff1db/cmd/clone.go#L681).

**To Reproduce**
1. I run `ghorg clone gitlab-examples/ops` (see https://gitlab.com/gitlab-examples/ops ), using [sample-conf.yaml](https://github.com/gabrie30/ghorg/blob/ed0955c9dd09b77329bfc4cece4fb97501cff1db/sample-conf.yaml) with the following modifications:
    ```
    GHORG_SCM_TYPE: gitlab
    GHORG_PRUNE: true
    GHORG_PRUNE_NO_CONFIRM: true
    ```
2. On [line 681 in clone.go](https://github.com/gabrie30/ghorg/blob/ed0955c9dd09b77329bfc4cece4fb97501cff1db/cmd/clone.go#L681) I get 
`f.Name() == "cluster-management"` while `repo.Name == "Cluster management"` for the theoretically matching repo. Thus, the prune step removes all the freshly cloned repositories.

3. With `GHORG_CLONE_WIKI: true` in config, the related `repo.Name` are empty.
4. Things got a bit trickier with `GHORG_PRESERVE_DIRECTORY_STRUCTURE: true`. In this case, `ghorg clonegitlab-examples/wayne-enterprises` (see https://gitlab.com/gitlab-examples/wayne-enterprises ), could be a better example, because there are more sub-groups. Now the [outputDirAbsolutePath](https://github.com/gabrie30/ghorg/blob/ed0955c9dd09b77329bfc4cece4fb97501cff1db/cmd/clone.go#L668) only directly contains wiki folders (I'm not sure if that's a bug or by-design), and thus it does not contain the necessary names again.

**Version info:** 
I'm using the [unreleased v1.7.17](https://github.com/gabrie30/ghorg/tree/ed0955c9dd09b77329bfc4cece4fb97501cff1db). 
Tested on Windows 10 but probably applies to every OS.

**Comment by gabrie30** [comment]
Thanks for raising these issues and including example repos to use, very helpful.

**Comment by gabrie30** [comment]
Going to close this issue, only #4 is not fixed but a warning has been added, which should be good enough for now.
