### ISSUE TITLE
Gitlab --preserve-dir creates two parent directories

### ISSUE THREAD

**Issue by llama0815** [gabrie30/ghorg#228]
**Describe the bug**
I'm downloading all the accessible projects by my organisation on gitlab.com. But ghorg stores them like this:
`{$organisation}\{$organisation}\{$group}\{$repository}` instead of just
`{$organisation}\{$group}\{$repository}`

**To Reproduce**
I haven't tried it with new groups but our links look like this:
`https://gitlab.com/{$organisation}/{$group}/{$repository}`

 ```
$ ghorg clone {$organisation} --preserve-dir

    *************************************
    * SCM           : gitlab
    * Type          : org
    * Protocol      : ssh
    * Location      : /Users/foo/ghorg/
    * Concurrency   : 25
    * Config Used   : /Users/foo/.config/ghorg/conf.yaml
    * Ghorg version : v1.8.2
    *************************************

XX repos found in {$organisation}
 ```

**Environment (please complete the following information):**
 - OS: MacOS 12.4

**Comment by gabrie30** [comment]
Thanks for reporting this

**Comment by gabrie30** [comment]
PR https://github.com/gabrie30/ghorg/pull/229 going to cut a new release, let me know if find any other issues!
