### ISSUE TITLE
Implement cloning of submodules using --recurse-submodules git clone command line option.

### ISSUE THREAD

**Issue by Antfere** [gabrie30/ghorg#234]
**Is your feature request related to a problem? Please describe.**
When cloning repositories that contain submodules, the submodule folder is cloned empty.

**Describe the solution you'd like**
If I am not mistaken, the git clone command line option: "--recurse-submodules" will fix this problem, it works when running git clone without ghorg at the very least. If you could make some ghorg command line option that implements --recurse-submodules on every git clone command ghorg makes, that would be very nice.

Thank you for your time.

**Comment by gabrie30** [comment]
Thanks for the feature request. Agreed, this would be nice.

**Comment by Antfere** [comment]
It works, thanks so much man.
