### ISSUE TITLE
Allow an option to disable the automatic --preserve-dir behavior

### ISSUE THREAD

**Issue by sding3** [gabrie30/ghorg#237]
**Is your feature request related to a problem? Please describe.**

Starting with [v1.8.3](https://github.com/gabrie30/ghorg/blob/master/CHANGELOG.md#183---7822), gitlab repos with conflicting names automatically trigger the ` --preserve-dir` behavior and there doesn't appear to be way to turn that off. Prior to v1.8.3, gitlab repos with conflicting names are cloned into a directory with a incrementing number appended to disambiguate. For deeply nested gitlab groups where there aren't that many repo name conflicts, the behavior prior to v1.8.3 is desirable.

**Describe the solution you'd like**

Do not automatically trigger the  `--preserve-dir` behavior. Only perform it if `--preserve-dir` (or the corresponding env var) has been supplied. Although this would be considered a BC breaking change. In the case that there are naming conflict, use the behavior from v1.8.2 which is to use a incrementing number suffix.

**Describe alternatives you've considered**

Afford a new optional configuration option, e.g. `--disable-aumatic-preserve-dir` (`GHORG_DISABLE_AUTOMATIC_PRESERVE_DIRECTORY_STRUCTURE`), to allow user to disable the implicit/automatic `--preserve-dir` behavior. This would maintain BC, but will be confusing. In the case that both `--disable-aumatic-preserve-dir` and `--preserve-dir` are supplied, this should probably be treated as an error.

**Comment by gabrie30** [comment]
Thanks for raising this issue. I added that feature when I noticed a different behavior when repo names collided. I wonder if thats a filesystem or git setting that's appending the numeral? In any case I didn't like the auto preserve-dir feature too much but I thought it was better than nothing.

I'm now thinking repos that collide will just have the full path appended. Something like `/foo/bar/baz` and `/ban/baz` would turn into `foo_bar_baz` and `ban_baz` in the output directory. I think it adds a bit more information to distinguish the two repos. Thoughts?

I'm also open to other suggestions on what to do with the collisions.

**Comment by sding3** [comment]
Oops I'm sorry, the "auto incrementing integer" actually corresponds to real repos named with those number suffixes. So the behavior with v1.8.2 is  that only one of set of repos with the same name would be cloned.

Yeah, I like turning the slashes into underscores. It's possible to lead secondary clashes, e.g. a repo has the path `foo_bar` and another repo with path `foo/bar` that gets translated into `foo_bar`, but this should be rare. I think using colons might decreases this chance even further (e.g. `foo:bar`), although colons are bit harder to type.

**Comment by gabrie30** [comment]
Ah good point, that would be a rare case. However, I think we'll be fine the repo names in the output dir use the repo slug, basically takes on the formatting of the name in its url. If the repo was Foo_Bar it would become foo-bar in the output dir, where as the foo/bar would become foo_bar if we use underscore.

**Comment by gabrie30** [comment]
@sding3 fix should be on master if you can build it and test let me know how it goes, kinda rushed this one so theres a good chance of bugs 😆

**Comment by sding3** [comment]
@gabrie30 - tested this morning and this works well - thank you!

**Comment by gabrie30** [comment]
Awesome thanks for confirming, if you have any ideas how to make it even better feel free to create another issue
