### ISSUE TITLE
--output-dir doesn't support absolute paths

### ISSUE THREAD

**Issue by peteward44** [gabrie30/ghorg#248]
Using --output-dir to specify an absolute path does not clone repos into expected directory

Example, ran from /home/user:
```
ghorg clone user --scm=gitlab --token=XX --preserve-dir --fetch-all --clone-type=user --output-dir=/mnt/disk0/gitlab-clone
```
Will clone repositories into /home/user/mnt/disk0/gitlab-clone, instead of /mnt/disk0/gitlab-clone as expected

 - OS: Ubuntu bionic X86_64

**Comment by gabrie30** [comment]
The `ABSOLUTE_PATH_TO_CLONE_TO` is the path it will clone to (--path) and the output dir is the name of the directory it clones into. I think what you want is 

```
ghorg clone user --scm=gitlab --token=XX --preserve-dir --fetch-all --clone-type=user --path=/mnt/disk0 --ouptput-dir=gitlab-clone
```

**Comment by gabrie30** [comment]
Here is some more [docs](https://github.com/gabrie30/ghorg#changing-clone-directories) on how the flags work

**Comment by gabrie30** [comment]
@peteward44 closing let me know if you run into any other issues

**Comment by peteward44** [comment]
Hi, thanks for your reply. That's useful, thankyou.
