### ISSUE TITLE
Clone all branches in separate folder & pull on each trigger?

### ISSUE THREAD

**Issue by 1stdevfriend** [gabrie30/ghorg#251]
This isn't a bug but I'm unable to figure this out. 

I've a server when I'm keeping backup of github project files. 
What I want to do is to have a repo folder and branches folder inside it 

which on next cronjob will git pull inside each folder

If there is anything you can suggest me. That'd be really helpful.

**Comment by gabrie30** [comment]
Hi @1stdevfriend thanks for raising this! There is a `--fetch-all` flag which will perform a `git fetch --all` on each repo. This will pull in all the branches from origin. 

If your org is on github.com you would need to run something like `ghorg clone yourorg --fetch-all --token=xxxxxx`

Does this fit your use case?

**Comment by 1stdevfriend** [comment]
Hi @gabrie30 Really a great piece of code!

Thank you so much. That solved my issue!
