### ISSUE TITLE
Ghorg creates (seemingly) pointless nested folder structure

### ISSUE THREAD

**Issue by MaxG87** [gabrie30/ghorg#267]
**Describe the bug**
I used `ghorg` to clone repositories from a self hosted Gitlab. I use the `--preserve-dir` switch. If I ask to clone project _some-project_ `ghorg` will create the folder structure `some-project/some-project/`. I find that very inconvenient and do not see a reason for this additional nesting.

I would be glad if the documentation could explain this behaviour or mention how to disable it.

**To Reproduce**
My `ghorg` command is:
`ghorg clone some-project --token some-token --scm gitlab --base-url https://gitlab.example.com/ --protocol ssh --preserve-dir`

1. Full command and details of the clone (removing your token) e.g.
```
+-+-+-+-+ +-+-+ +-+-+-+-+-+
|T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : gitlab
* Type          : org
* Protocol      : ssh
* Location      : /home/mgoerner/ghorg/
* Concurrency   : 25
* Base URL      : https://gitlab.example.com/
* Preserve Dir  : true
* Config Used   : none
* Ghorg version : v1.9.1
*************************************
43 repos found in bpo

Success cloning repo: 
```
  
**Environment (please complete the following information):**
 - OS: Debian Testing

**Comment by gabrie30** [comment]
Is this the same behavior you are experiencing? https://github.com/gabrie30/ghorg/issues/228

What is the project structure on your gitlab instance? Is it nested with the same project name as well?

Using `--preserve-dir` will preserve the directory structure for all projects within the group you are cloning. If omit the `--preserve-dir` flag all the repos in that group will be cloned into the same directory.

**Comment by MaxG87** [comment]
It looks related but I think it is not a duplicate. I use `ghorg`  with a self-hosted Gitlab instance. The duplicated folder is a group, not the organisation.

My URI would be `https://gitlab.example.com/{group}/{subgroup}/{project}`. Sometimes the nesting is deeper. The parent folder I experience would be `{group}/{group}/{subgroup}/{project}`.

**Comment by gabrie30** [comment]
Thanks again, should be fixed @MaxG87 let me know if you run into any issues

**Comment by MaxG87** [comment]
I just gave it a try. It works and is gorgeous. Thank you very much.
