### ISSUE TITLE
Version 1.9.2 does not clone into groupname directory anymore together with preserve dir

### ISSUE THREAD

**Issue by nudgegoonies** [gabrie30/ghorg#271]
With version 1.9.1 this still worked.

I have this configuration:
```
GHORG_SCM_TYPE: gitlab
GHORG_CLONE_PROTOCOL: ssh
GHORG_ABSOLUTE_PATH_TO_CLONE_TO: /home/nudgegoonies/git
GHORG_OUTPUT_DIR: mygroups
GHORG_CLONE_TYPE: org
GHORG_SCM_BASE_URL: https://$COMPANYINSTANCE
GHORG_INCLUDE_SUBMODULES: false
GHORG_PRUNE: true
GHORG_PRUNE_NO_CONFIRM: false
GHORG_COLOR: enabled
GHORG_SKIP_ARCHIVED: true
GHORG_SKIP_FORKS: false
GHORG_BACKUP: false
GHORG_CONCURRENCY: 2
GHORG_NO_CLEAN: true
GHORG_CLONE_WIKI: false
GHORG_FETCH_ALL: true
GHORG_QUIET: false
GHORG_DRY_RUN: false
GHORG_EXIT_CODE_ON_CLONE_INFOS: 0
GHORG_EXIT_CODE_ON_CLONE_ISSUES: 1
GHORG_GITLAB_TOKEN: $SECRET
GHORG_PRESERVE_DIRECTORY_STRUCTURE: true
GHORG_RECLONE_VERBOSE: false
GHORG_RECLONE_QUIET: false
```
When i run `ghorg clone groupname` the repos where cloned into `~/git/mygroups/$GROUPNAME/$SUBGROUPNAME/$PROJECTNAME` with 1.9.1.
With 1.9.2 they are cloned into `~/git/mygroups/$SUBGROUPNAME/$PROJECTNAME`.
As you can see, the groupname directory is missing since 1.9.2.

**Comment by nudgegoonies** [comment]
Thank you for the answer. Our company is running GitLab Enterprise Edition 15.5.5-ee.

**Comment by gabrie30** [comment]
@nudgegoonies I wasn't able to reproduce this. One reason could be that with ee edition I can only test against the latest image. Will leave this open to see if anyone else has the similar experience, or if you are able to provide more details on the command your running and what the directory structure of your gitlab instance is.

**Comment by gabrie30** [comment]
@nudgegoonies the fix should be in the main branch and will be in 1.8.3 when released

**Comment by gabrie30** [comment]
@nudgegoonies the more I think about this I think the current way it does it in 1.8.2 seems more correct. In your example you'll always have a folder with one directory in it at this path `~/git/mygroups/$GROUPNAME`

It makes more sense for `--output-dir` to take the name of what the folder would be called by default, in your case `groupname, however you override that with the output dir set to mygroups.

I think the better option for you would be to set your `--path` to `~/git/mygroups` and not use the output dir

I'm going to think about this a bit more.

**Comment by gabrie30** [comment]
Alternatively you could do `ghorg clone groupname/subgroupname --output-dir=mygroups --preserve-dir`

**Comment by gabrie30** [comment]
@nudgegoonies new release it out with the fix let me know if you run into any issues.

**Comment by nudgegoonies** [comment]
@gabrie30 Thank you for your work. I tried to reproduce the issue with gitlab.com with this config:
```
GHORG_SCM_TYPE: gitlab
GHORG_CLONE_PROTOCOL: ssh
GHORG_ABSOLUTE_PATH_TO_CLONE_TO: /home/nudgegoonies/git
GHORG_OUTPUT_DIR: mygroups
GHORG_CLONE_TYPE: org
GHORG_INCLUDE_SUBMODULES: false
GHORG_PRUNE: true
GHORG_PRUNE_NO_CONFIRM: false
GHORG_COLOR: enabled
GHORG_SKIP_ARCHIVED: true
GHORG_SKIP_FORKS: false
GHORG_BACKUP: false
GHORG_CONCURRENCY: 2
GHORG_NO_CLEAN: true
GHORG_CLONE_WIKI: false
GHORG_FETCH_ALL: true
GHORG_QUIET: false
GHORG_DRY_RUN: false
GHORG_EXIT_CODE_ON_CLONE_INFOS: 0
GHORG_EXIT_CODE_ON_CLONE_ISSUES: 1
GHORG_GITLAB_TOKEN: $SECRET
GHORG_PRESERVE_DIRECTORY_STRUCTURE: true
GHORG_RECLONE_VERBOSE: false
GHORG_RECLONE_QUIET: false
```
Then i ran `ghorg clone gitlab-org` and i there i can reproduce the issue with 1.9.1 and 1.9.3!
I would expect `~/git/mygroups/gitlab-org/$SUBGROUPNAME/$PROJECTNAME` but i get `~/git/mygroups/$SUBGROUPNAME/$PROJECTNAME` etc.
I don't know why it worked with 1.9.1 on our company gitlab because it fails on gitlab.com with both 1.9.1 and 1.9.3!

**Comment by gabrie30** [comment]
Ya thats the expected behavior, unless theres a good reason to reconsider it, I'm open to suggestions.

But we now have tests so there shouldn't be any regressions moving forward.

**Comment by nudgegoonies** [comment]
This is strange. I consider mixed repositories from different groups lying within the same GHORG_OUTPUT_DIR without groupnames as an unsorted mess and want them to be cloned into the groupname directory to match the structure on gitlab. In my opinion there should be at least an option to have the correct behavior of 1.9.1 with gitlab-ee.

**Comment by gabrie30** [comment]
> I consider mixed repositories from different groups lying within the same GHORG_OUTPUT_DIR without groupnames as an unsorted mess

That is the behavior without the `--preserve-dir` flag. It will clone all repos into one directory.

If you want to preserve the directory structure you can use the `--preserve-dir`, when you use `--output-dir` the default directory name ghorg creates is just renamed to the name given via the output dir.

Sounds like you want to clone a specific subgroup, you can do that as well. `ghorg clone group/subgroup` this will create the behavior you are after.

**Comment by nudgegoonies** [comment]
Thanks a lot. GHORG_PRESERVE_DIRECTORY_STRUCTURE was always true but i misunderstood GHORG_OUTPUT_DIR. I removed GHORG_OUTPUT_DIR and added that path to GHORG_ABSOLUTE_PATH_TO_CLONE_TO and now it works with 1.9.3. Now i understand, that it was a bug that it worked, for whatever reason, with 1.9.1 with our company gitlab-ee.

**Comment by gabrie30** [comment]
Yea adding integration tests for GitLab was long overdue and should now prevent the behavior from changing moving forward.
