### ISSUE TITLE
When using git and keepassxc with git-credential-keepassxc ghorg creates masses of oauth2 entries in keepassxc

### ISSUE THREAD

**Issue by nudgegoonies** [gabrie30/ghorg#286]
I configured https://github.com/Frederick888/git-credential-keepassxc to use keepassxc for my gitlab personal access token.
I changed from ssh to https for all my gitlab repositores with ghorg and git on the console and via intellij works flawless.

When using ghorg there are masses of duplicated entries for our internal gitlab server with the username oauth2 stored in the group "KeePassXC-Browser Passwords".  Strange, because the git group configured by git-credential-keepassxc is named "git".

It sounds like there is a bug in git-credential-keepassxc storing git credentials in the group "KeePassXC-Browser Passwords" instead of the the group "git" configured by git-credential-keepassxc. But why does git-credential-keepassxc store something in keepassxc when called via ghorg? Could it be that ghorg calls git with the token configured in the ghorg configuration file?

I use Debian 11, git 2.30.2, git-credential-keepassxc 0.12 , keepassxc 2.7.4 and ghorg .

**Comment by gabrie30** [comment]
I dont know much about keepassxc but my initial thought is it has something to do with the command that runs below. Its an old feature of ghorg which auto look ups a token in the users keystore.

Can you replicate the issue by running the following command manually? https://github.com/gabrie30/ghorg/blob/master/configs/configs.go#L204
