### ISSUE TITLE
Problem cloning private Repositories from GitHub when using "fine-grained tokens"

### ISSUE THREAD

**Issue by verybadsoldier** [gabrie30/ghorg#290]
**Describe the bug**
When running ghorg to clone my Github repos using a Github "fine-grained token" then I get a list of failed repos at the end. All those failing repos are my private repos:

![image](https://user-images.githubusercontent.com/364469/227791711-269f51bc-5305-48e9-8e6e-4a79e70b206e.png)

When doing the same with a classical token, then everything works as expected.

**To Reproduce**
I run it like this:
```
O:\Meine Ablage\AppData\Duplicati>ghorg clone verybadsoldier --backup -c user -t my-kewl-fine-grained-token -p f:\testghorg

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : github
* Type          : user
* Protocol      : https
* Location      : f:\testghorg\
* Concurrency   : 25
* Backup        : true
* Config Used   : none
* Ghorg version : v1.9.3
*************************************

Cloning all your public/private repos. This process may take a bit longer than other clones, please be patient...
93 repos found in verybadsoldier

Success updating remote repo: https://github.com/verybadsoldier/docker-iptables_stats.git -> branch: master
Success updating remote repo: https://github.com/verybadsoldier/CloudProxy.git -> branch: master
Success updating remote repo: https://github.com/verybadsoldier/docker-springrts-build.git -> branch: master
...
============ Issues ============
<Errors here as shown in the screenshot>
```

**Additional Context**
When using a fined-grained token with plain `git` then this also works as expected:
```
O:\Meine Ablage\AppData\Duplicati>git clone https://verybadsoldier:my-kewl-fine-grained-token@github.com/verybadsoldier/my-secret-private-repo.git f:\testclone
Cloning into 'f:\testclone'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 11 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), 5.07 KiB | 5.07 MiB/s, done.
```

**Environment (please complete the following information):**
I am on Windows 10.

**Comment by verybadsoldier** [comment]
That's how my token looks in GitHub:
![image](https://user-images.githubusercontent.com/364469/227795000-7634dbdd-94e4-4269-9ef3-9e71c06468aa.png)

**Comment by gabrie30** [comment]
Does your token have the correct permissions? I'm not totally sure what permissions need to be included.

Based on that screen shot I would try to enable some of the user permissions. When cloning user repos it will may need something like "user read repos"

**Comment by verybadsoldier** [comment]
Hey! Yes, but as said: using the exact same token with the plain `git` command it works fine. So I think the token should be ok.

**Comment by gabrie30** [comment]
Can you try using 1.9.4? It's on the main branch.

**Comment by gabrie30** [comment]
Thanks, I'm able to reproduce locally

**Comment by gabrie30** [comment]
So when ghorg clones it does not use the username, seems like with these new tokens you need to add the username

ghorg clones like this

```
git clone https://github_pat_xxxxxxxxxxxxxx@github.com/gabrie30/private.git --mirror
```

This will wait for a password

However if you use the username like you did it works fine. Also for public repos username is not needed.

**Comment by gabrie30** [comment]
I'm wondering if the token just needs like user profile access along with repo access that way it can assume the username and not need it in the clone url

**Comment by verybadsoldier** [comment]
Ok, thank you! From the git log, it seems you fixed something in that regard? I will happily test and give feedback, but I am unsure  how I could run ghorg from the branch. But if it helps, I will surely find out.

**Comment by gabrie30** [comment]
I'll just cut a new release then. Should be available shortly

**Comment by verybadsoldier** [comment]
Tested 1.9.4 and it works like a charm, big thanks!

**Comment by gabrie30** [comment]
Thanks for the follow up and reporting the issue @verybadsoldier!
