### ISSUE TITLE
enhancement: add optionj to omit token

### ISSUE THREAD

**Issue by 6543** [gabrie30/ghorg#294]
e.g. you want to clone from a public gitlab instance but it has registration disabled. you still should be able to backup public faced repos ...

# workaround
use own compiled version with apply diff:
```diff 
diff --git a/configs/configs.go b/configs/configs.go
index 049927a..b53a6db 100644
--- a/configs/configs.go
+++ b/configs/configs.go
@@ -243,10 +243,6 @@ func VerifyTokenSet() error {
                return ErrNoGitHubToken
        }
 
-       if scmProvider == "gitlab" && os.Getenv("GHORG_GITLAB_TOKEN") == "" {
-               return ErrNoGitLabToken
-       }
-
        if scmProvider == "gitea" && os.Getenv("GHORG_GITEA_TOKEN") == "" {
                return ErrNoGiteaToken
        }
```

# what i expect

instead of an error,  a warning that the token is missing and only public stuff can be fetched (... on github also mention api rate limits ...)

**Comment by gabrie30** [comment]
I could be missing something but ghorg gets a list of repos to clone by performing a GET on something like a /org/repos endpoint. This requirement to use an api makes the token required. I'm not sure theres a way to get a list of repos without using the SCM's API.

Maybe for a local/on prem gitlab instance if the api auth is disabled this would work.

**Comment by 6543** [comment]
Gitea and gitlab do not require a token ... you just have limited (public) access

**Comment by 6543** [comment]
*there exist instances **that do** require a token in any case, but that is an individual setting by the instance admin (require_login=true)

**Comment by gabrie30** [comment]
I think this would make things confusing for users trying to clone an org that has public api access then trying to do the same thing to an org that does not have it enabled.

**Comment by 6543** [comment]
well at least, adding an option to do without, else you have to compile ghorg yourselve each time you hit that case

**Comment by gabrie30** [comment]
That seems reasonable

**Comment by gabrie30** [comment]
@6543 made some changes if you want to try them out

**Comment by 6543** [comment]
Yes that fix it, thanks
