### ISSUE TITLE
"Could not find a valid github token" when trying to authenticate with github app

### ISSUE THREAD

**Issue by duizabojul** [gabrie30/ghorg#310]
I got the following error if I try to use authentication through Github app:

`Could not find a valid github token. GHORG_GITHUB_TOKEN or (--token, -t) flag must be set. Create a personal access token, then set it in your $HOME/.config/ghorg/conf.yaml or use the (--token, -t) flag, see 'GitHub Setup' in README.md`

I have to set `GHORG_NO_TOKEN=true` to bypass this check. Then the backup works well 👍

**Comment by gabrie30** [comment]
Thanks, this should be fixed.
