### ISSUE TITLE
I have a space in my Group name

### ISSUE THREAD

**Issue by a6k7rii** [gabrie30/ghorg#316]
**Please check the following resources before opening an issue**

1. Review the [troubelshooting section](https://github.com/gabrie30/ghorg#troubleshooting) in the README.md
1. Review the [examples](https://github.com/gabrie30/ghorg/tree/master/examples) directory for example commands

**Describe the bug**
I have a space in my group name and ghorg clone command cannot find the repo.

**To Reproduce**
1. Full command and details of the clone (removing your token) e.g.
    ```
      $ ghorg clone "AWS XXX" --scm=gitlab --token=xxxxxxxxxxxxxx --preserve-dir

    ```

1. Details on the user/org you tried to clone e.g. is it your user, a public org, etc.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS Ventura

**Additional context**

**Comment by gabrie30** [comment]
The name can have spaces but the path will have dashes, just use `AWS-XXX` instead. Let me know if this does not work.

**Comment by a6k7rii** [comment]
It's still the same error. Is there a way where we can give the URL Of the Group Instead of the Group name?

**Comment by gabrie30** [comment]
The path is the slug of the URL, so if its `https://mygitlab.com/groups/AWS-XXX` then the group name to use is `AWS-XXX`
if the path is `aws-xxx` than try the lowercase. If both of these do not work can you provide more information on the gitlab you are using. Is it cloud or hosted. If hosted what version is it running?

**Comment by a6k7rii** [comment]
It is a cloud Gitlab Enterprise edition 16.1.0. 

The URL for the group ends with /aws but the Group name is "AWS XXX" I tried the command with lower case aws but still it cannot find the group. 

Will try adding GHORG_DEBUG=true while giving it a shot next time.

**Comment by gabrie30** [comment]
Here are the [docs](https://github.com/gabrie30/ghorg/blob/master/examples/gitlab.md#cloud-gitlab-orgs) on gitlab cloud. Have you followed these?

Seems like you are missing the org name

Would be something like 

 ```
ghorg clone myorg/aws --scm=gitlab --token=xxxxxxxxxxxxxx --preserve-dir
```

Or if you can share the URL to the group I can give you the full command.

**Comment by a6k7rii** [comment]
I have read the docs and found out what I overlooked, i was thinking gitlab-examples to be a group instead of Org. Everything sorted now. Thanks for the support.
