### ISSUE TITLE
Help text mentions ~/ghorg for configurations

### ISSUE THREAD

**Issue by MaxG87** [gabrie30/ghorg#322]
Hi,

I was a bit annoyed that `ghorg`'s help text mentioned that the configuration is in `$HOME/ghorg/` instead of being in `$HOME/.config/ghorg`. I wanted to open an issue for that, but found #65 . This is great! However, the wrong configuration file is still referenced in a help text.

```
$ ghorg version
v1.9.6
$ ghorg clone --help | head -n1
Clone user or org repos from GitHub, GitLab, Gitea or Bitbucket. See $HOME/ghorg/conf.yaml for defaults, its likely you will need to update some of these values of use the flags to overwrite them. Values are set first by a default value, then based off what is set in $HOME/ghorg/conf.yaml, finally the cli flags, which have the highest level of precedence.
```

Is it possible that the documentation wasn't updated?

**Comment by gabrie30** [comment]
Thanks for raising this! Yes it must have gotten missed. Fix will be in the next release.
