### ISSUE TITLE
Don't drop local changes

### ISSUE THREAD

**Issue by exic** [gabrie30/ghorg#324]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I reclone (to be sure other repositories are up-to-date) and my local changes are gone.

**Describe the solution you'd like**
An option (should be "don't reset" per default imo) to enable/disable resetting the project on pull.

**Describe alternatives you've considered**
I've looked for existing options..

**Comment by gabrie30** [comment]
I think you want to use `GHORG_NO_CLEAN`

**Comment by exic** [comment]
Ha, right. Day must have been too long, thanks for pointing it out. 😃
