### ISSUE TITLE
Help text doesn't show synopsis

### ISSUE THREAD

**Issue by MaxG87** [gabrie30/ghorg#325]
I wanted to run `ghorg clone` today. I had a command line in my history using `ghorg clone all-groups`, so I started to use this. However, I quickly noticed that it downloaded too many irrelevant repositories, so I wanted to be more specific.

Unfortunately, `ghorg clone --help` was not helpful at all. In particular, it has only one mentioning of _group_ at all. Neither does the help text explain what `all-groups` would do, nor does it mention alternatives. I had to resort to the projects README and examples to find out what could be done.

The examples are great, btw. However, I think one should have a fair chance to learn what to do by reading `--help`.

**Comment by gabrie30** [comment]
Wondering if there was a way to make like a `ghorg --help-gitlab` flag that would be the same as the markdown in the examples directory. That way the documentation would be written once and rendered in two places. I don't want to maintain 2 different sets of documentation.

What do you think, any other ideas?

**Comment by MaxG87** [comment]
I mainly write Python and Bash and are not familiar with what Go offers. In Python there are great libraries that make it very easy to generate CLI interfaces with documentation. In particular, they generate a correct and complete synopsis.

I am completely with you, duplicating the extensive documentation would be awful. However, I think giving a complete synopsis with, optionally, brief descriptions is feasible. You can point the reader to your very helpful Github documentation in that, I think.
