### ISSUE TITLE
Don't make assumptions about where to clone to

### ISSUE THREAD

**Issue by prologic** [gabrie30/ghorg#35]
Please don't make assumptions about where I'd like the cloned repos to go to.

Currently I can configure the environment variable `GHORG_ABSOLUTE_PATH_TO_CLONE_TO` for example:

```#!bash
$ GHORG_GITHUB_TOKEN="${GITHUB_TOKEN}" GHORG_ABSOLUTE_PATH_TO_CLONE_TO="$(pwd)" ghorg myorg
```

But this insists on cloning the repos to `$PWD/myorg_ghorg/...`

It would be nice if ghorg had flags and arguments as opposed to just relying on the environment and/or a config file. See #34

**Comment by gabrie30** [comment]
Addcobra #36 addresses this issue
