### ISSUE TITLE
Automated Docker Image release

### ISSUE THREAD

**Issue by afonsoc12** [gabrie30/ghorg#351]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A Docker image that would be built as part of releases

**Describe alternatives you've considered**
I build my own image of ghorg [afonsoc12/docker-ghorg](https://github.com/afonsoc12/docker-ghorg) but it's been giving me some headache lately. I would like very much to port this GH action to the original repo.

**Additional context**
Happy to work on this if you are keen on merging it. Plan is to use GH actions and release to ghcr

**Comment by gabrie30** [comment]
Great idea, we should probably have two images that get built. One triggering when a new tag is created this would happen for every release the tag being the release version. Then additionally when theres a push to master which would be for the unreleased version, could use the tag unreleased or prerelease something like that. Thoughts?

**Comment by afonsoc12** [comment]
I agree, that makes sense!

I came across [this action](https://github.com/docker/metadata-action) and I believe we could follow that format. We would have images built for PRs, tags, master and adhoc runs. 

Alternatively, if this is an overkill number of images, we can create the following tags, depending on the events:
- master: `master` and `master-<commit SHA>`
- tags: `latest` and `vX.X.X`

The plan would be to have a reusable workflow, that you can call after a release or after a commit to master. The inputs would be a selector `is_release` or something similar.

On another note, I have noticed that [goreleaser](./.github/workflows/goreleaser.yml) workflow will runs regardless of [go](./.github/workflows/go.yml) WF. Is this expected?
