### ISSUE TITLE
ghorg displays wrong config file when using conf.yml

### ISSUE THREAD

**Issue by afonsoc12** [gabrie30/ghorg#357]
**Please check the following resources before opening an issue**

1. Review the [troubelshooting section](https://github.com/gabrie30/ghorg#troubleshooting) in the README.md
1. Review the [examples](https://github.com/gabrie30/ghorg/tree/master/examples) directory for example commands

**Describe the bug**
ghorg looks for `conf.yaml` file inside `~/.config`. It also works if the file is named `conf.yml`. However, it always displays `conf.yaml`.

**To Reproduce**

1. Create a conf.yml inside ~/.config
2. Full command and details of the clone (removing your token) e.g.
    ```
      $ GHORG_DEBUG=1 ghorg clone kubernetes --match-prefix=sig
      -------- Setting Default ENV values ---------
      (...)
      GHORG_GITHUB_TOKEN: <TOKEN> # Read correctly from conf.yml
      (...)
      GHORG_CONFIG SET TO: /Users/<USER>/.config/ghorg/conf.yaml # File is named conf.yml
      
       +-+-+-+-+ +-+-+ +-+-+-+-+-+
       |T|I|M|E| |T|O| |G|H|O|R|G|
       +-+-+-+-+ +-+-+ +-+-+-+-+-+
      
      *************************************
      * SCM           : github
      * Type          : org
      * Protocol      : ssh
      * Location      : <DEST>
      * Concurrency   : 25
      * Wikis         : true
      * Prefix Match  : sig
      * Submodules    : true
      * No Clean      : true
      * Config Used   : /Users/<USER>/.config/ghorg/conf.yaml # Again, file is named conf.yml
      * Ghorg version : v1.9.9
      *************************************
      Filtering repos down by including prefix matches...
      3 repos found in kubernetes, including 0 enabled wikis
      
      (...)
      
      Success cloning repo: git@github.com:kubernetes/sig-testing.git -> branch: master
      Success cloning repo: git@github.com:kubernetes/sig-security.git -> branch: main
      Success cloning repo: git@github.com:kubernetes/sig-release.git -> branch: master
      New repos cloned: 3, existing repos pulled: 0
      
      Finished! <DEST PATH>
    ```

**Environment (please complete the following information):**
 - macOS 14, ghorg v1.9.9

**Comment by gabrie30** [comment]
Thanks for raising this, I'll take a look when I get some time.

**Comment by gabrie30** [comment]
I would assume this is something that the package viper does. It probably looks for both yml and yaml and just standardizes on yaml 

Heres where its setting the default conf file https://github.com/gabrie30/ghorg/blob/master/cmd/root.go#L192 

Considering it likely has to do with this package there isn't much we can do.
