### ISSUE TITLE
local gitea requires password

### ISSUE THREAD

**Issue by llama0815** [gabrie30/ghorg#381]
**Please check the following resources before opening an issue**

1. Review the [troubelshooting section](https://github.com/gabrie30/ghorg#troubleshooting) in the README.md - **done**
1. Review the [examples](https://github.com/gabrie30/ghorg/tree/master/examples) directory for example commands - **done**

Cloning regularly `git clone http://<localip>:3000/<org>/<repo>.git` works with every device without any authentication.  
Organization is public and repo not private.

**Describe the bug**
Cloning an organisation requires password despite providing full access API token.

**To Reproduce**

Setup gitea on another local docker server. Try to clone a public organisation:
```
ghorg clone <organization> --scm=gitea --base-url=http://<localip>:3000 --insecure-gitea-client --token=<full_access_token>

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : gitea
* Type          : org
* Protocol      : ssh
* Location      : /Users/<user>/ghorg/
* Concurrency   : 25
* Base URL      : http://<localip>:3000
* Preserve Dir  : true
* Config Used   : /Users/<user>/.config/ghorg/conf.yaml
* Ghorg version : v1.9.9
*************************************
WARNING: USING AN INSECURE GITEA CLIENT
1 repos found in <organization>

git@<localip>'s password:
```

**Screenshots**

**Environment**
 - MacOS

**Additional context**

Also cloning user keeps looping the error message.

```
ghorg clone <user> --clone-type=user --base-url=http://<localip>:3000 --token=<full_access_token> --insecure-gitea-clieng
<...>
Error getting repo for user: <user>Error getting repo for user: <user>
Error getting repo for user: <user>Error getting repo for user: <user>
Error getting repo for user: <user>Error getting repo for user: <user>
...
```

**Comment by gabrie30** [comment]
The first issue seems like an issue with git, are you able to do a git clone without ghorg using the ssh protocol?

**Comment by llama0815** [comment]
My problem was, that I had set `GHORG_CLONE_PROTOCOL: https` inside my config.

This command is working now:
`ghorg clone <organization> --scm=gitea --protocol=https --base-url=http://<localip>:3000 --insecure-gitea-client --token=<api_token>`

I managed to get ssh protocol working too. But there is a mess due to my gitea & ssh configuration which isn't covered by ghorg.

Just in case someone else stumbles here:
DockerHost ssh `<localip>:22`
gitea ssh `<localip>:222` web `<localip>:3000`

```
$ ~/.ssh/config
Host dockerhost
    Hostname <localip>
    User <user>
    IdentityFile ~/.ssh/<ssh-key>
    Port 22

Host <localip> # alias don't work!
    Hostname <localip>
    User git
    IdentityFile ~/.ssh/<ssh-key>
    Port 222
```
Working command:
`ghorg clone <organization> --scm=gitea --protocol=ssh --base-url=http://<localip>:3000 --insecure-gitea-client --token=<api_token>`
