### ISSUE TITLE
Asset names in checksum file are different from asset names in GitHub Releases

### ISSUE THREAD

**Issue by suzuki-shunsuke** [gabrie30/ghorg#382]
https://github.com/gabrie30/ghorg/releases/tag/v1.9.9

[checksums.txt](https://github.com/gabrie30/ghorg/releases/download/v1.9.9/checksums.txt)

```
4978cb4c0965813314dfc8454c93144336f2dd681db2f502c579e5f4aff5aee6  ghorg_Darwin_arm64.tar.gz
4ca21e8c2ba57f68621fe0b5bd2fe3801f1c11bff6588d87a5562538b58f8273  ghorg_Linux_arm64.tar.gz
7790e3e29c1e4ecb0ecc7cfc4b11a17e3247ab799ec9d48025d0d90b2bee8de9  ghorg_Linux_x86_64.tar.gz
99458b6541b82aa353eea900e42f40cb0ee8f290795d2d75b9affb7d0d22139e  ghorg_Linux_i386.tar.gz
b0e29471dd1753c0824075b6065ababaedad79a1187e68b1dff6f26df908648e  ghorg_Windows_i386.tar.gz
b186bdabb9595e655818a9b8f01d937fc1e9c8f890981bbf93b40a3a15208def  ghorg_Darwin_x86_64.tar.gz
c093391a219159bc4aa2849c422b38846362d74b61a4f5f7f3ac42d03db0d06e  ghorg_Windows_x86_64.tar.gz
dc183ad43d98f49397c8c1a3490b527e7ff76a9705f603411297c7f8aee0cc9e  ghorg_Windows_arm64.tar.gz
```

Release assets

ghorg_1.9.9_Darwin_arm64.tar.gz
ghorg_1.9.9_Darwin_x86_64.tar.gz
ghorg_1.9.9_Linux_arm64.tar.gz
ghorg_1.9.9_Linux_i386.tar.gz
ghorg_1.9.9_Linux_x86_64.tar.gz
ghorg_1.9.9_Windows_arm64.tar.gz
ghorg_1.9.9_Windows_i386.tar.gz
ghorg_1.9.9_Windows_x86_64.tar.gz

Asset names in checksum file are different from asset names in GitHub Releases, so we can't verify checksums.

**Comment by gabrie30** [comment]
Hi thanks for reporting this. It was because of this https://github.com/gabrie30/ghorg/issues/342 

I'll cut a new release so a new checksum is created.
