### ISSUE TITLE
ghorg failing with exit code 128 depending on target folder

### ISSUE THREAD

**Issue by lapete** [gabrie30/ghorg#389]
**Describe the bug**
I can only clone my organisation's repositories when `GHORG_ABSOLUTE_PATH_TO_CLONE_TO` is a path that is created by ghorg.

``` bash
ls -l ~ | grep code
drwxr-xr-x 15 arbeit arbeit    4096 Feb  1 16:07 code

$ ls -l ~/code
drwx------  3 arbeit arbeit 4096 Feb  1 16:07 ght
drwxr-xr-x  4 arbeit arbeit 4096 Feb  1 16:05 phoenix
```
(shortened output)

My organisation's main folder is called phoenix. When I set  `GHORG_ABSOLUTE_PATH_TO_CLONE_TO` to /home/arbeit/code/, I get a few hundred lines of `Problem setting remote with credentials Repo: customer_configurations Error: exit status 128`. Ghorg seems to be able to read the project repositories but can't clone them.
When I set the var to /home/arbeit/code/ght, _a folder that was created by ghorg_, it works as intended and clones all the repos that exited with error 128 before.

**Workaround:**
1. Moved the whole ~/code folder elsewhere and ran ghorg again so ghorg would create ~/code
2. Set  `GHORG_ABSOLUTE_PATH_TO_CLONE_TO` to /home/arbeit/code
3. Ran `ghorg reclone` which features 2 sub(sub)projects in phoenix.
4. ghorg created ~/code/phoenix/firstproject and cloned all repos succesfully
5. ghorg created ~/code/phoenix/secondproject/somefolder and cloned all repos succesfully

It seems like the different folder permissions cause ghorg some trouble.
I added another subproject of phoenix to my `reclone.yaml` and ran reclone again, which worked and added the third project correctly.

**Details on the user/org you tried to clone e.g. is it your user, a public org, etc.**

- Selfhosted Gitlab
- `GHORG_SCM_TYPE: gitlab`
- `GHORG_CLONE_PROTOCOL: ssh`
- `GHORG_OUTPUT_DIR` is empty
- `GHORG_CLONE_TYPE: org`
- Large/nested repository structures (ran with `GHORG_PRESERVE_DIRECTORY_STRUCTURE: true`)

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Arch Linux
 - ghorg version: 1.9.9 (installed via AUR)

**Comment by gabrie30** [comment]
The problem seems to be setting the remote for the repo that already exists in that directory. If you can cd into one of those repos and then try to set the remote yourself you will see the same problem.

Try running `git remote set-url origin <repo_clone_url>` in one of the repos. This will be your problem.
