### ISSUE TITLE
Cloning inside docker container with ssh protocol not working

### ISSUE THREAD

**Issue by fey** [gabrie30/ghorg#406]
**Describe the bug**
Clone repos with ssh protocol inside docker container `ghcr.io/gabrie30/ghorg` not working

**To Reproduce**
1. Full command and details of the clone (removing your token) e.g.
```
docker run -u : --rm \
-v $(pwd):/data \
-v /home/feycot/.ssh:/home/ghorg/.ssh \
ghcr.io/gabrie30/ghorg:latest \
clone fey \
--scm=github \
--clone-type=user \
--token=<token> \
--protocol=ssh \
--preserve-dir

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : github
* Type          : user
* Protocol      : ssh
* Location      : /data/
* Concurrency   : 25
* Preserve Dir  : true
* Config Used   : /config/conf.yaml
* Ghorg version : v1.9.11
*************************************

Cloning all your public/private repos. This process may take a bit longer than other clones, please be patient...
226 repos found in fey

============ Issues ============

Problem trying to clone Repo: git@github.com:fey/ansible-sandbox.git Error: exit status 128
Problem trying to clone Repo: git@github.com:fey/booklibrary.git Error: exit status 128
Problem trying to clone Repo: git@github.com:fey/1983-Restoration.git Error: exit status 128
# ...
```
    
If i clone with default https protocol, it work well
```
docker run -u : --rm \
-v /tmp/ghorg-test:/data/hexlethq \
-v /home/feycot/.ssh:/home/ghorg/.ssh \
ghcr.io/gabrie30/ghorg:latest \
clone fey \
--scm=github \
--clone-type=user \
--token=ghp_ZFFxxxxxxxxxxxxxxxxxxxxxxxxxx \
--preserve-dir

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : github
* Type          : user
* Protocol      : https
* Location      : /data/
* Concurrency   : 25
* Preserve Dir  : true
* Config Used   : /config/conf.yaml
* Ghorg version : v1.9.11
*************************************

Cloning all your public/private repos. This process may take a bit longer than other clones, please be patient...
226 repos found in fey

Success cloning repo: https://github.com/fey/awesome-underhood.git -> branch: main
Success cloning repo: https://github.com/fey/ansible-role-dbeaver.git -> branch: master
```

1. Details on the user/org you tried to clone e.g. is it your user, a public org, etc
    https://github.com/fey

**Environment (please complete the following information):**
 - OS: Linux Mint 21.3 x86_64
 - Docker version 26.1.0, build 9714adc

**Comment by gabrie30** [comment]
@fey thanks for raising this issue, looks like in your second example there is a github token, im not sure if this is active or not but wanted to let you know asap

**Comment by fey** [comment]
@gabrie30 thank you! Github sent me email and removed the token

**Comment by gabrie30** [comment]
Added the ssh-client to the image so that was definitely missing. Also the ssh config needs to be mounted to `/home/.ssh` rather than `/home/ghorg/.ssh` I'm sure there is a way to change this but its not in the image. But even still if you have a a passphrase on your ssh keys you'll need to enter it for each clone. I'm sure theres a way to fix this too but not sure the fruit is worth the squeeze if https works. Interesting issue tho, thanks again for bringing it up.

**Comment by fey** [comment]
Thank you, I tested with image based on ghorg's official. It work well
