### ISSUE TITLE
Add more logging with enabled debug mode

### ISSUE THREAD

**Issue by fey** [gabrie30/ghorg#408]
**Is your feature request related to a problem? Please describe.**
I have issues with downloading repositories inside docker image. I dont know what is problem - with permissions, ssh or something else..

**Describe the solution you'd like**

Add more output from git with enabled debug

**Describe alternatives you've considered**
-

**Additional context**
Output with enabled debug:
```
------------- GIT DEBUG -------------
(exec.Cmd) /usr/bin/git clone git@gitlab.hexlet.io:hexlethq/boilerplates/java_example_user_project.git /tmp/hexlethq/boilerplates/java_example_user_project

============ Issues ============

Problem trying to clone Repo: git@gitlab.hexlet.io:hexlethq/boilerplates/go_example_project.git Error: exit status 128
...
```

**Comment by gabrie30** [comment]
As far as gits error message on clones I believe we already return as much information as we can.

**Comment by fey** [comment]
When I used a Docker container, I ran into access issues on the file system. Unfortunately ghorg did not display this information and I had to manually run git clone to see what the problem was. Is there any way to output this kind of information when using ghorg?  :thinking:

**Comment by gabrie30** [comment]
@fey I added some more logging in the git commands if you wanted to try it out

**Comment by fey** [comment]
Thank you, it works well!
