### ISSUE TITLE
Is it possible to specify the GitLab instance?

### ISSUE THREAD

**Issue by angristan** [gabrie30/ghorg#41]
Or is gitlab.com hardcoded? I couldn't find it in the source code.

**Comment by gabrie30** [comment]
Uses the github.com/xanzy/go-gitlab library, which looks like allows you to change the base url

https://github.com/gabrie30/ghorg/blob/master/cmd/clone_gitlab.go

**Comment by gabrie30** [comment]
@angristan just pushed some changes to master, go get the newest code update your $HOME/ghorg/conf.yaml and try setting the --base-url flag, you can also update the GHORG_SCM_BASE_URL in the conf.yaml

eg.

`ghorg clone someorg --scm=gitlab --base-url=https://myhostedgitlab.com`

let me know how it goes

**Comment by angristan** [comment]
Thanks!

Although I get `No repos found for gitlab org: ...`. Is there a way to debug this?

**Comment by gabrie30** [comment]
I only briefly looked at the gitlab library. Does your base-url look similar to 

`https://git.mydomain.com/api/v3`

This is from the example in the gitlab client

To debug I'd probably spit out the results from the call above this line, I do need to improve the error handling.

https://github.com/gabrie30/ghorg/blob/master/cmd/clone_gitlab.go#L40

**Comment by gabrie30** [comment]
@angristan made some updates on master to hopefully show you the error. Let me know how it goes.

**Comment by angristan** [comment]
Yes, it works, `https://` was missing from my `GHORG_SCM_BASE_URL`.

Thanks :)

**Comment by gabrie30** [comment]
Awesome thanks for suggesting this addition!
