### ISSUE TITLE
Blacklists repos or option to ignore GitHub archived repos

### ISSUE THREAD

**Issue by verybadsoldier** [gabrie30/ghorg#42]
I have several repos on GitHub which I forked a while ago but I don't want to backup them cause my changes are minimal or maybe even merged upstream. So I would like an ability to exclude some repos when fetching from e.g. GitHub.

**Describe the solution you'd like**
I would like being to able pass a list of repository names for the script to ignore. So it will grab all my GitHub repos but I want to exclude some manually. 

Or maybe being able to set a flag so the script will only grab non-archived repositories from GitHub. I could possible archive my lesser repositories on GitHub and the script would automatically ignore them.

Thanks for this project! I am new to this but I like it!

**Comment by verybadsoldier** [comment]
When I think more about it I actually prefer the option to make ghorg ignore archived GitHub repositories so I could easily clean up my GitHub account by using the archive function and ghorg will act accordingly.

**Comment by gabrie30** [comment]
Thanks for the feature request! 

I think both are great ideas. 

It would be neat to have something like a .gitignore, ".ghorgignore" maybe, in the $HOME/ghorg directory, this file could be a list of repos to ignore while cloning.

Secondly, a flag something like `--no-archived` that would skip any archived repos.

**Comment by gabrie30** [comment]
@verybadsoldier added these two features into master and updated the readme, see the ignoring repos section. I'll leave this open until you'll able to try it out, let me know how it goes

**Comment by verybadsoldier** [comment]
Wow, that's great, you are fast!
I'll happily give it a try soonish (like today or in the next days). Thanks!

**Comment by verybadsoldier** [comment]
Yes, works great! Only thing I had to figure out was that the parameter is `--skip-archived` (instead of `--no-archvied`) but then it worked flawlessly, thanks alot!
