### ISSUE TITLE
Option to select GitHub "type" parameter

### ISSUE THREAD

**Issue by anton-kotik** [gabrie30/ghorg#429]
Right now, there's no way to clone only GitHub repositories where you are the owner.

Current GitHub API request: https://api.github.com/users/anton-kotik/repos?per_page=100&type=all
Correct GitHub API request: https://api.github.com/users/anton-kotik/repos?per_page=100&type=owner

**Describe the solution you'd like**
For example, command option `--github-type=owner` (default: `all`). Possible values: all / owner / member. 

**Additional context**
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user

**Comment by gabrie30** [comment]
Thanks for raising this, sounds like a good idea
