### ISSUE TITLE
Ability to use --mirror when cloning

### ISSUE THREAD

**Issue by verybadsoldier** [gabrie30/ghorg#43]
Well sorry, but another idea that could help to make good backups:

I am using `ghorg` to make backups of GitHub and GitLab projects and it would be nice if it would be possible to clone the repos using the `--mirror` parameter of `git clone`. In that case you get a bare repo and for example you don't get a working copy (which is not needed for the backup).

So in that case also the branch parameter would not be needed. 

When starting `ghorg` and the repos already exist locally they could be updated using `git remote update`.

Thank you!

**Comment by gabrie30** [comment]
Fixed with #44
