### ISSUE TITLE
More information for: Username for 'https://gitlab.com': 

### ISSUE THREAD

**Issue by optii** [gabrie30/ghorg#46]
**Describe the bug**
You are already aware of the bug, but i would like to give some more insight, I believe this occurs on gitlab when using http & having 2fa enable on the account.

I don't have time at the moment to dig deeper into it, let me know if you want some more details & when i have 5 i will get them to you

**Comment by gabrie30** [comment]
@optii thanks for this. I don't use gitlab, so whatever information you can provide would be very helpful. Also, what do you think would be the best fix/improvements for users?

**Comment by gabrie30** [comment]
@optii this should be resolved with the latest version. Can reopen if you still see the error after upgrading.
