### ISSUE TITLE
Maintain Project Structure as in Version Control

### ISSUE THREAD

**Issue by tvvignesh** [gabrie30/ghorg#47]
It would be great to maintain the same folder structure as in Gitlab - org/groups/subgroups/repository

When cloned, all the repos get converted to a flat structure and then we have to end up organizing it. Would be great if the tool can do it itself.

**Comment by gabrie30** [comment]
@tvvignesh @ArmandoAssuncao this feature has been added to master and can be accomplished using the `--preserve-dir` flag

**Comment by defunctzombie** [comment]
Seems the CLI option is setting the wrong variable:

https://github.com/gabrie30/ghorg/blob/924b57b624556a899913e821f3da679d5b4f5b46/cmd/clone.go#L51
