### ISSUE TITLE
ghorg hangs after update (>=1.9.1)

### ISSUE THREAD

**Issue by jeffrson** [gabrie30/ghorg#472]
**Please check the following resources before opening an issue**

1. Review the [troubelshooting section](https://github.com/gabrie30/ghorg#troubleshooting) in the README.md
1. Review the [examples](https://github.com/gabrie30/ghorg/tree/master/examples) directory for example commands

**Describe the bug**

ghorg stopped working for me after I updated. I had a rather old version (1.6?) which used to work. Now after update it stopped after writing version:
```
...
* Ghorg version : v1.9.1
*************************************
```

v1.9.0 still works for me.
v1.9.1 just appears to wait without doing anything.
v1.11.0 shows a running "spinner".

Even after `GHORG_DEBUG=true` it does not behave different (just shows environment variables before "TIME TO GHORG").

I'm executing it as `ghorg clone all-groups` which should clone (or update) Gitlab repositories:

```
*************************************
* SCM           : gitlab
* Type          : org
* Protocol      : https
* Location      : /backups/ghorg/
* Concurrency   : 1
* Backup        : true
* Wikis         : true
* Ghorgignore   : /home/user/.config/ghorg/ghorgignore
* Output Dir    : gitlab
* Fetch All     : true
* Preserve Dir  : true
* Config Used   : /home/user/.config/ghorg/conf.yaml
* Ghorg version : v1.11.0
*************************************
```

I have no idea how to look further :-(

**Comment by gabrie30** [comment]
Interesting what version of gitlab are you on? Theres no obvious code changes in those ghorg versions, however the gitlab client was upgraded 2 minor versions. My best guess would be the version of gitlab you are running was no longer supported by the gitlab client apis.

**Comment by jeffrson** [comment]
Oh, I'm sorry I did not mention that.

I'm working against gitlab.com (SaaS). So it should be as current as possible (currently 17.6.0-pre).

**Comment by jeffrson** [comment]
Looks like it only happens with "all-groups" or "all-users", not with single groups or single user.

BTW, for some reason, ghorg does not append "_backup" anymore to the destination directory name (with --backup or GHORG_BACKUP set).

**Comment by jeffrson** [comment]
Well, I found the "problem". It's this commit: https://github.com/gabrie30/ghorg/commit/fa495fa4241397c68f83580274179fcdf3a0b126 (in current source: https://github.com/gabrie30/ghorg/blob/master/scm/gitlab.go#L125) - since there are **a lot** of groups on gitlab.com. For me, it helps to add `Owned: gitlab.Bool(true),` - but I don't know if this will behave as intended. Maybe it should become a configuration?

**Comment by jeffrson** [comment]
So finally I made a reclone.yaml.

Previously we had a lot of top level groups, which we migrated into one about two years ago, so I don't need all-groups anyway :-)

Thanks!

**Comment by alexpyc** [comment]
I am wondering if instead of `AllAvailable` or `Owned`, the option of `MinAccessLevel` can be used. It can limit the extent to those repositories the user has access to. Which in my current case, I am figuring out how to move many groups at once

https://docs.gitlab.com/ee/api/groups.html#list-groups
