### ISSUE TITLE
Issue when spacing not given in conf.yaml file

### ISSUE THREAD

**Issue by tvvignesh** [gabrie30/ghorg#48]
If the values are given in conf.yaml file after colon (:) without a space, it gives a parse error for the yaml file even though its valid. Works only when space is given.

**Comment by gabrie30** [comment]
I haven't looked at the yaml spec however below is considered invalid yaml from an online parser. 

```
--- 
foo:bar
martin: 
  job: Developer
  name: "Martin D'vloper"
```

**Comment by tvvignesh** [comment]
@gabrie30 Oops. My bad. Didn't realize that. Thanks. Closing this issue.
