### ISSUE TITLE
Token not taken from conf.yaml file

### ISSUE THREAD

**Issue by tvvignesh** [gabrie30/ghorg#49]
If I specify the gitlab access token in conf.yaml file, it does not work but if I supply the same token as a command line argument, it works. Looks like there is some issue in retrieving the access token from conf.yaml file.

For me when I tried `security find-internet-password -s gitlab.com  | grep "acct" | awk -F\" '{ print $4 }'` it did not work since I do not have security installed and have not added they keys to the linux keychain.

But I guess that should not be an issue since I anyway gave the access token in the file.

**Comment by gabrie30** [comment]
Thanks for pointing this out. I've updated master, you should be good to go. If you can verify its working as expected i'll close this out.

**Comment by tvvignesh** [comment]
Sure. Closing this. Thanks.
