### ISSUE TITLE
branch HEAD is not using master

### ISSUE THREAD

**Issue by dojo90** [gabrie30/ghorg#51]
If you want to clone to **HEAD** branch, the result is always **master**

1. checkout a new branch `foo` (from the master; current leading branch) and make a commit
2. use `--branch=HEAD` as argument

**Expected behavior**
The repository should be cloned including changes of branch `foo`

**Comment by gabrie30** [comment]
From my understanding HEAD is just a reference to a branch, it is not actually a branch. That being said I'm not sure it makes sense to add this to the --branch flag.

Curious what the use case is here. I'm assuming you want to be able to clone all repos, then navigate to a repo in your ghorg directory check out a branch then be able to run ghorg again and it resets that branch from origin?

If thats the case maybe a new flag would be a better solution. Something like `--preserve-branch`

**Comment by dojo90** [comment]
I would like to clone the repos up to and including the last commit without first having to specify the individual branches. So as per definition:

> The HEAD in Git is the pointer to the current branch reference, which is in turn a pointer to the last commit you made or the last commit that was checked out into your working directory. That also means it will be the parent of the next commit you do.

So if you set `--branch=HEAD` or `--HEAD=true` flag, it will automatically be pulled to the last commit. Hope it is now clearly what I want to do. Always clone the a repo including the latest commits.

**Comment by gabrie30** [comment]
ghorg now uses the default branch when none is specified
