### ISSUE TITLE
Homebrew install fails

### ISSUE THREAD

**Issue by override80** [gabrie30/ghorg#61]
**Describe the bug**
I cannot get ghorg to install on my OSX via homebrew, tried both with go 1.14 and downgrading to 1.13 (this might no be the issue however).

**To Reproduce**
brew install gabrie30/utils/ghorg

**Expected behavior**
Habe ghorg installed and working

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 10.13.6

**Additional context**
`go
build
-o
/usr/local/Cellar/ghorg/1.2.0/bin/ghorg
.

# github.com/korovkin/limiter
SIGILL: illegal instruction
PC=0x1064dc0 m=4 sigcode=1

goroutine 24 [running]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc000689d18 sp=0xc000689d10 pc=0x1064dc0
cmd/compile/internal/ssa.liveValues(0xc0006f0160, 0xc000690706, 0x2, 0x2, 0xc00069a000, 0x1c, 0x4e, 0xc00069c000, 0x5, 0x20)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/ssa/deadcode.go:153 +0xcea fp=0xc000689e68 sp=0xc000689d18 pc=0x123b05a
cmd/compile/internal/ssa.deadcode(0xc0006f0160)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/ssa/deadcode.go:215 +0x277 fp=0xc00068a100 sp=0xc000689e68 pc=0x123b6e7
cmd/compile/internal/ssa.Compile(0xc0006f0160)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/ssa/compile.go:92 +0x9a5 fp=0xc00068dd40 sp=0xc00068a100 pc=0x1232495
cmd/compile/internal/gc.buildssa(0xc000078c60, 0x3, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/ssa.go:445 +0xcd8 fp=0xc00068ded0 sp=0xc00068dd40 pc=0x18e5af8
cmd/compile/internal/gc.compileSSA(0xc000078c60, 0x3)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/pgen.go:298 +0x5d fp=0xc00068df98 sp=0xc00068ded0 pc=0x18ae7cd
cmd/compile/internal/gc.compileFunctions.func2(0xc00039d0e0, 0xc0000b47f0, 0x3)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/pgen.go:363 +0x49 fp=0xc00068dfc8 sp=0xc00068df98 pc=0x1976009
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00068dfd0 sp=0xc00068dfc8 pc=0x1063551
created by cmd/compile/internal/gc.compileFunctions
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/pgen.go:361 +0x128

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0000b47f8)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0000b47f0)
	/usr/local/Cellar/go/1.14/libexec/src/sync/waitgroup.go:130 +0x64
cmd/compile/internal/gc.compileFunctions()
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/pgen.go:373 +0x1ce
cmd/compile/internal/gc.Main(0x1a9a908)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/main.go:724 +0x33a5
main.main()
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/main.go:52 +0xac

rax    0x1
rbx    0xc000568dc8
rcx    0x1c
rdx    0xc000568e20
rdi    0xc00069c130
rsi    0xc000690706
rbp    0xc000689e58
rsp    0xc000689d10
r8     0x2
r9     0x2
r10    0xc000568ab8
r11    0x0
r12    0xc00069a000
r13    0xc00069a006
r14    0xc00069c100
r15    0x20
rip    0x1064dc0
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0
# github.com/hashicorp/hcl/hcl/strconv
SIGILL: illegal instruction
PC=0x1064dc0 m=0 sigcode=1

goroutine 1 [running]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc000166e48 sp=0xc000166e40 pc=0x1064dc0
cmd/compile/internal/gc.walkcompare(0xc0003b9480, 0xc000167598, 0xc0003ad300)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/walk.go:3073 +0x9 fp=0xc000166e50 sp=0xc000166e48 pc=0x196d639
cmd/compile/internal/gc.walkexpr(0xc0003b9480, 0xc000167598, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/walk.go:556 +0x6476 fp=0xc0001674a8 sp=0xc000166e50 pc=0x195a886
cmd/compile/internal/gc.walkstmt(0xc0003b9180, 0xc0003b9200)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/walk.go:254 +0xf09 fp=0xc000167658 sp=0xc0001674a8 pc=0x1953089
cmd/compile/internal/gc.walkstmtlist(0xc000572900, 0x5, 0x8)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/walk.go:80 +0x46 fp=0xc000167680 sp=0xc000167658 pc=0x1952086
cmd/compile/internal/gc.walk(0xc0001042c0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/walk.go:64 +0x3b0 fp=0xc000167788 sp=0xc000167680 pc=0x1951bd0
cmd/compile/internal/gc.compile(0xc0001042c0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/pgen.go:236 +0x6b fp=0xc000167800 sp=0xc000167788 pc=0x18ae43b
cmd/compile/internal/gc.funccompile(0xc0001042c0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/pgen.go:222 +0xc1 fp=0xc000167858 sp=0xc000167800 pc=0x18ae2c1
cmd/compile/internal/gc.Main(0x1a9a908)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/internal/gc/main.go:714 +0x3299 fp=0xc000167f10 sp=0xc000167858 pc=0x1886379
main.main()
	/usr/local/Cellar/go/1.14/libexec/src/cmd/compile/main.go:52 +0xac fp=0xc000167f88 sp=0xc000167f10 pc=0x19c57cc
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:203 +0x212 fp=0xc000167fe0 sp=0xc000167f88 pc=0x10348d2
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000167fe8 sp=0xc000167fe0 pc=0x1063551

rax    0xc000167598
rbx    0x0
rcx    0xc000000180
rdx    0x3c
rdi    0xc0003b9480
rsi    0xc0003b9490
rbp    0xc000167498
rsp    0xc000166e40
r8     0x14
r9     0xfffffffb
r10    0x260
r11    0x11
r12    0x18
r13    0x0
r14    0x1c291a4
r15    0x0
rip    0x1064dc0
rflags 0x10293
cs     0x2b
fs     0x0
gs     0x0
SIGILL: illegal instruction
PC=0x1065ae0 m=10 sigcode=1

goroutine 7 [running]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc0000bbe70 sp=0xc0000bbe68 pc=0x1065ae0
cmd/go/internal/work.(*Builder).Do.func2(0xc0005ac3c0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:142 +0x12c fp=0xc0000bbf10 sp=0xc0000bbe70 pc=0x147d8dc
cmd/go/internal/work.(*Builder).Do.func3(0xc000500204, 0xc000153360, 0xc00000eb60)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:178 +0x76 fp=0xc0000bbfc8 sp=0xc0000bbf10 pc=0x147dc36
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000bbfd0 sp=0xc0000bbfc8 pc=0x1064271
created by cmd/go/internal/work.(*Builder).Do
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:165 +0x38a

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000500204)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc000500204)
	/usr/local/Cellar/go/1.14/libexec/src/sync/waitgroup.go:130 +0x64
cmd/go/internal/work.(*Builder).Do(0xc000153360, 0xc000592000)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:187 +0x3ae
cmd/go/internal/work.runBuild(0x1ac4fe0, 0xc00010e090, 0x1, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/build.go:420 +0x6a2
main.main()
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/main.go:189 +0x569

goroutine 6 [runnable]:
syscall.syscall(0x10b08b0, 0xf, 0xc0005f4e50, 0x8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/sys_darwin.go:63 +0x2e
syscall.readlen(0xf, 0xc0005f4e50, 0x8, 0x12, 0xc000232000, 0x60)
	/usr/local/Cellar/go/1.14/libexec/src/syscall/syscall_darwin.go:364 +0x62
syscall.forkExec(0xc0002fbe00, 0x3b, 0xc0001e6a20, 0x11, 0x12, 0xc0005f4f70, 0x5f, 0xf5b2b00020400, 0xc000290000)
	/usr/local/Cellar/go/1.14/libexec/src/syscall/exec_unix.go:210 +0x3c6
syscall.StartProcess(...)
	/usr/local/Cellar/go/1.14/libexec/src/syscall/exec_unix.go:248
os.startProcess(0xc0002fbe00, 0x3b, 0xc0001e6a20, 0x11, 0x12, 0xc0005f5108, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec_posix.go:52 +0x2c0
os.StartProcess(0xc0002fbe00, 0x3b, 0xc0001e6a20, 0x11, 0x12, 0xc0005f5108, 0x60, 0x0, 0xc0005f5004)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec.go:102 +0x7c
os/exec.(*Cmd).Start(0xc00029cdc0, 0x8031df0, 0x1ea3201c7375)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:417 +0x50c
os/exec.(*Cmd).Run(0xc00029cdc0, 0x1297c297, 0x1acefe0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:337 +0x2b
cmd/go/internal/work.(*Builder).runOut(0xc000153360, 0xc0005a4280, 0xc0003e0910, 0x4e, 0x0, 0x0, 0x0, 0xc000350e00, 0x14, 0x1c, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:1928 +0x5bc
cmd/go/internal/work.(*Builder).run(0xc000153360, 0xc0005a4280, 0xc0003e0910, 0x4e, 0xc000248ae1, 0x15, 0x0, 0x0, 0x0, 0xc000350e00, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:1853 +0xb5
cmd/go/internal/work.gcToolchain.symabis.func1(0xc00027a000, 0xc0003bc480, 0x3, 0x3, 0xc00002ade0, 0x2b, 0x2b, 0x1f)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/gc.go:299 +0x32a
cmd/go/internal/work.gcToolchain.symabis(0xc000153360, 0xc0005a4280, 0xc0003bc480, 0x3, 0x3, 0x282, 0x4f9, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/gc.go:306 +0x12b
cmd/go/internal/work.(*Builder).build(0xc000153360, 0xc0005a4280, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:642 +0x120b
cmd/go/internal/work.(*Builder).Do.func2(0xc0005a4280)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:118 +0x358
cmd/go/internal/work.(*Builder).Do.func3(0xc000500204, 0xc000153360, 0xc00000eb60)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:178 +0x76
created by cmd/go/internal/work.(*Builder).Do
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:165 +0x38a

goroutine 8 [syscall]:
syscall.syscall6(0x10b0640, 0x6376, 0xc00056cfd4, 0x0, 0xc000558090, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/sys_darwin.go:74 +0x2e
syscall.wait4(0x6376, 0xc00056cfd4, 0x0, 0xc000558090, 0x90, 0x1620ae0, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x6376, 0xc00056d024, 0x0, 0xc000558090, 0x1578460, 0x0, 0x100000104f123)
	/usr/local/Cellar/go/1.14/libexec/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc000421470, 0x1680820, 0x1680828, 0x1680818)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec_unix.go:38 +0x7b
os.(*Process).Wait(...)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc0003fcb00, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:502 +0x60
os/exec.(*Cmd).Run(0xc0003fcb00, 0x121387e7, 0x1acefe0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:340 +0x5c
cmd/go/internal/work.(*Builder).runOut(0xc000153360, 0xc000597400, 0xc0003a2360, 0x58, 0x0, 0x0, 0x0, 0xc0002ca3c0, 0xf, 0x14, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:1928 +0x5bc
cmd/go/internal/work.gcToolchain.gc(0xc000153360, 0xc000597400, 0xc0004211a0, 0x2b, 0xc000170480, 0x2df, 0x413, 0x0, 0x0, 0xc00056d500, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/gc.go:142 +0xc98
cmd/go/internal/work.(*Builder).build(0xc000153360, 0xc000597400, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:678 +0x1715
cmd/go/internal/work.(*Builder).Do.func2(0xc000597400)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:118 +0x358
cmd/go/internal/work.(*Builder).Do.func3(0xc000500204, 0xc000153360, 0xc00000eb60)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:178 +0x76
created by cmd/go/internal/work.(*Builder).Do
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:165 +0x38a

goroutine 9 [chan receive]:
os/exec.(*Cmd).Wait(0xc0003fc9a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:510 +0x125
os/exec.(*Cmd).Run(0xc0003fc9a0, 0x113ae2ea, 0x1acefe0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:340 +0x5c
cmd/go/internal/work.(*Builder).runOut(0xc000153360, 0xc000597040, 0xc00052d080, 0x71, 0x0, 0x0, 0x0, 0xc0002ca3c0, 0x11, 0x14, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:1928 +0x5bc
cmd/go/internal/work.gcToolchain.gc(0xc000153360, 0xc000597040, 0xc00002b710, 0x2b, 0xc00017a1c0, 0x61, 0xd1, 0x0, 0x0, 0xc00056f500, ...)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/gc.go:142 +0xc98
cmd/go/internal/work.(*Builder).build(0xc000153360, 0xc000597040, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:678 +0x1715
cmd/go/internal/work.(*Builder).Do.func2(0xc000597040)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:118 +0x358
cmd/go/internal/work.(*Builder).Do.func3(0xc000500204, 0xc000153360, 0xc00000eb60)
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:178 +0x76
created by cmd/go/internal/work.(*Builder).Do
	/usr/local/Cellar/go/1.14/libexec/src/cmd/go/internal/work/exec.go:165 +0x38a

goroutine 55 [IO wait]:
internal/poll.runtime_pollWait(0x9259508, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0001369d8, 0x72, 0x201, 0x200, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001369c0, 0xc0001ce000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_unix.go:169 +0x201
os.(*File).read(...)
	/usr/local/Cellar/go/1.14/libexec/src/os/file_unix.go:263
os.(*File).Read(0xc000524898, 0xc0001ce000, 0x200, 0x200, 0x1046dd2, 0xc0001365c8, 0xc00004aea0)
	/usr/local/Cellar/go/1.14/libexec/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc00046e570, 0x172c8e0, 0xc000524898, 0x9215300, 0xc00046e570, 0xc00004af01)
	/usr/local/Cellar/go/1.14/libexec/src/bytes/buffer.go:204 +0xb1
io.copyBuffer(0x172bd00, 0xc00046e570, 0x172c8e0, 0xc000524898, 0x0, 0x0, 0x0, 0x1006b35, 0xc000136720, 0xc00004afb0)
	/usr/local/Cellar/go/1.14/libexec/src/io/io.go:391 +0x2fc
io.Copy(...)
	/usr/local/Cellar/go/1.14/libexec/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0xc000136720, 0xc00004afb0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:310 +0x63
os/exec.(*Cmd).Start.func1(0xc0003fcb00, 0xc0003ba1a0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:436 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:435 +0x608

goroutine 27 [runnable]:
internal/poll.runtime_pollWait(0x9259c08, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0004835d8, 0x72, 0x201, 0x200, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004835c0, 0xc0000aa400, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_unix.go:169 +0x201
os.(*File).read(...)
	/usr/local/Cellar/go/1.14/libexec/src/os/file_unix.go:263
os.(*File).Read(0xc0004d62d8, 0xc0000aa400, 0x200, 0x200, 0x0, 0x0, 0xc0005096a0)
	/usr/local/Cellar/go/1.14/libexec/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc0003bca50, 0x172c8e0, 0xc0004d62d8, 0x9215300, 0xc0003bca50, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/bytes/buffer.go:204 +0xb1
io.copyBuffer(0x172bd00, 0xc0003bca50, 0x172c8e0, 0xc0004d62d8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/io/io.go:391 +0x2fc
io.Copy(...)
	/usr/local/Cellar/go/1.14/libexec/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:310 +0x63
os/exec.(*Cmd).Start.func1(0xc0003fc9a0, 0xc0002f69e0)
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:436 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.14/libexec/src/os/exec/exec.go:435 +0x608

rax    0xb
rbx    0xc000592000
rcx    0xc000153360
rdx    0xc000349380
rdi    0x8
rsi    0xc0005ac3c0
rbp    0xc0000bbf00
rsp    0xc0000bbe68
r8     0xc0005c0780
r9     0x17
r10    0x16
r11    0x0
r12    0x0
r13    0x26
r14    0x25
r15    0x100
rip    0x1065ae0
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0

HOMEBREW_VERSION: 2.2.9-23-g78140ce
ORIGIN: https://github.com/Homebrew/brew
HEAD: 78140cef4aea88c693d7f28a9ff6f8c288d0b944
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abde67b1e88d2872b5eb26cfd1ba4589bc7e0c71
Core tap last commit: 39 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/me/Library/Caches/Homebrew
HOMEBREW_LOGS: /Users/me/Library/Logs/Homebrew
CPU: quad-core 64-bit nehalem
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/go/bin:/usr/bin:/bin:/usr/sbin:/sbin
`

**Comment by gabrie30** [comment]
Unfortunately I have no idea how to fix this without being able to fiddle with it. 

The formula is working for me locally with OSX 10.15.2. 

I've also tried the formula on a fresh mac install and it properly installed.

Are you able to install other formulas using brew?

**Comment by override80** [comment]
Hi gabrie, it looks like it might be connected to this issue: https://github.com/golang/go/issues/37459. So it's a go issue, i'll be waiting for mileston 1.14.1 from brew to fix it ;) Thanks!
