### ISSUE TITLE
Prompt for password when use api token

### ISSUE THREAD

**Issue by Lolek1978** [gabrie30/ghorg#63]
Describe the bug
When cloning from GitLab over https, I'm prompted to enter a password since the token is recognized as username.

Screenshots
The log is:

 +-+-+-+-+ +-+-+ +-+-+-+-+-+
 |T|I|M|E| |T|O| |G|H|O|R|G|
 +-+-+-+-+ +-+-+ +-+-+-+-+-+

*************************************
* SCM           : gitlab
* Type          : org
* Protocol      : https
* Branch        : master
* Location      : /home/osboxes/Desktop/
* Concurrency   : 25
* Base URL      : https://git.pl/api/v4
* Backup        : true
*************************************

118 repos found in 316

*************************************

7 repos found in my-org

Password for 'https://token@git.pl': 

Prompt for password multiple times.

Desktop (please complete the following information):

OS: ubuntu
osboxes@mail:~/d00b$ brew install gabrie30/utils/ghorg
Warning: gabrie30/utils/ghorg 1.2.0 is already installed and up-to-date
To reinstall 1.2.0, run `brew reinstall ghorg` 

I don't know how to install the latest version of ghorg :(.

Additional context
The used GitLab account is configured with 2FA.

**Comment by gabrie30** [comment]
have you tried cloning via ssh? have you tried using the --token flag? have you tried adding your token to your ghorg.conf? what command are you running?

**Comment by gabrie30** [comment]
follow the go instructions for the most recent version, make sure you delete the brew binary first

**Comment by Lolek1978** [comment]
> have you tried cloning via ssh? 

I dont have acces to gitlab via ssh :(. 

>have you tried using the --token flag? 

Yes. Currently i ran with token flag.

>have you tried adding your token to your ghorg.conf? what command are you running?

I installed ghorg with :

----
osboxes@mail:~$ brew install gabrie30/utils/ghorg
==> Installing ghorg from gabrie30/utils
==> Downloading https://github.com/gabrie30/ghorg/archive/1.2.0.tar.gz
...
=> https://raw.githubusercontent.com/gabrie30/ghorg/master/sample-conf.yaml
==> ***************************
==> 
🍺  /home/osboxes/.linuxbrew/Cellar/ghorg/1.2.0: 3 files, 16.5MB, built in 25 seconds

------
and run with 
ghorg clone 316 --base-url=https://git.pl/api/v4 -s gitlab -t <token> --namespace=apigee/gateway

I tried to also add <token> to ghorg.conf but i have still issue.


I read in changelog that you have 1.2.2 version but at releeases site i still see 1.2.0 - maybe thats the issue?

**Comment by gabrie30** [comment]
> btw. your soft is great :)

Thank you so much! 

I think you are correct and will cut a new release tonight.

**Comment by gabrie30** [comment]
@Lolek1978 1.2.2 should now be available through brew, could you try the new version and let me know if it fixes your issue?

**Comment by Lolek1978** [comment]
Hey, I checked again.

I uninstalled and installed version 1.2.2.

Now everything works :).

Thanks again for a great job :-)

**Comment by agathebower** [comment]
I had ghorg load the repos to the same dir, where the ghorg-binary was sitting... using another directory did the trick!
