### ISSUE TITLE
Personal Access Token persisted to git remotes

### ISSUE THREAD

**Issue by mcinerney** [gabrie30/ghorg#64]
I've recently started using ghorg again (thanks for an amazing tool!)

I noticed today when looking at a recent _ghorg_ that my personal access token has been persisted to the origin remote address which isn't something I'd expect with generally using the credential helper on OSX for git actions.

**To Reproduce**
1. Run ghorg on an organization
2. cd in ~/Desktop/${ORG}_ghorg/${REPO}
3. run `git remote -v` (or check repo/.gitconfig/config)
4. See personal access token it all its glory

**Expected behavior**
PATs to not be stored unencrypted on my machine

**Comment by gabrie30** [comment]
Thanks @mcinerney! Master has been updated with the fix and will be included in the next release.
