### ISSUE TITLE
Should use $XDG_CONFIG_HOME/ghorg for config file

### ISSUE THREAD

**Issue by liljenstolpe** [gabrie30/ghorg#65]
**Is your feature request related to a problem? Please describe.**
On most !OSX unix-like boxen $XDG_CONFIG_HOME (usually $HOME/.config) is a single place to look for all of your application configuration files, making it easy to version control, etc.  Having ghorg use $HOME/ghorg leads to a messier $HOME, and yet one more place to hoover things up.

**Describe the solution you'd like**

If $XDG_CONFIG_HOME is defined, store your configs in $XDG_CONFIG_HOME/ghorg.  Otherwise, default - probably to $HOME/.config/ghorg - a number of CLI OSX applications use that now, as well.

**Describe alternatives you've considered**

Symlinks... :(

**Additional context**

**Comment by gabrie30** [comment]
Changes are now on master and will be included in the next release. Please let me know if you find any issues. Thanks again @liljenstolpe!

**Comment by liljenstolpe** [comment]
Thank's @gabrie30
