### ISSUE TITLE
Support Github enterprise URL.

### ISSUE THREAD

**Issue by ignazioc** [gabrie30/ghorg#71]
**Is your feature request related to a problem? Please describe.**
I'd like to clone the repos stored on a github enterprise instance. For doing this I should be able to customize the base url for Github SCM, but this is currently limited only to GitLab.

**Describe the solution you'd like**
I'd like to provide the base URL or a github enterprise instance.

**Describe alternatives you've considered**
I considered writing a custom script to clone all the repo :) but then I found this.

**Comment by gabrie30** [comment]
This would be an easy feature to introduce if the github library used https://github.com/google/go-github had a way to update the base-url. As a result this will be a much larger feature to introduce and will likely not be added in the near future.
