### ISSUE TITLE
Support for cloning repos anonymously 

### ISSUE THREAD

**Issue by sbuvaneshkumar** [gabrie30/ghorg#73]
Currently ghorg doesn't support cloning repos anonymously.
An example:
```
அ  ~  ghorg clone debian --scm=gitlab --base-url=https://salsa.debian.org --preserve-dir
Could not find a valid gitlab token. GHORG_GITLAB_TOKEN or (--token, -t) flag must be set. Create a token from gitlab then set it in your $HOME/ghorg/conf.yaml or use the (--token, -t) flag...For best results read the troubleshooting section of README.md https://github.com/gabrie30/ghorg to properly store your token in the osx keychain
```
It will be much better if ghorg can run without providing Gitlab token, as it is not needed for anonymous cloning.

**Comment by gabrie30** [comment]
Ghorg needs a token because it uses the gitlab api to get all the repos for the org. If gitlabs api did not an api token to use then we could add this feature. Closing this because its unlikely gitlab will offer that.
