### ISSUE TITLE
Clone repos from a group recursively

### ISSUE THREAD

**Issue by OperationalFallacy** [gabrie30/ghorg#88]
Hi,

Maybe I missed something, but cloning gitlab group only pulls repos in the group itself.
Subgroups are not cloned, is it expected?

`ghorg cone --base-url https://gitlab.company.org --scm=gitlab -p /work --token=$token --preserve-dir group_name` 

Thanks!
Roman

**Comment by gabrie30** [comment]
No that is not expected, I would expect it to also clone the subgroups. Does your token have access to the subgroups?

**Comment by OperationalFallacy** [comment]
It should, I mean I can clone repos if specific group/subgroup is used

**Comment by gabrie30** [comment]
The token will need `api` scopes

**Comment by gabrie30** [comment]
Did you get this sorted out? Just cut a new release if you are using brew.

**Comment by OperationalFallacy** [comment]
Sorry, got another problem with prompts for username/password 🤷 
I'm temporarily on a windows laptop, running things in docker which is a total disaster to run on windows, its all probably going to work just fine on mac.

**Comment by gabrie30** [comment]
If you have a ssh key for gitlab you can try `--protocol=ssh`
