### ISSUE TITLE
add documentation for gitea

### ISSUE THREAD

**Issue by gabrie30** [gabrie30/ghorg#94]
**Is your feature request related to a problem? Please describe.**
Currently there are no examples on how to use gitea or how to initially set it up

**Describe the solution you'd like**
Update ./examples to have a gitea.md with how to use and also update the [readme](https://github.com/gabrie30/ghorg#setup-and-configuration) to include gitea setup and configuration

**Comment by 6543** [comment]
you can assign me if you like :)

**Comment by 6543** [comment]
@gabrie30 does  #95 solve this?

or what info is needed?
