### ISSUE TITLE
Golang Installation Failed!

### ISSUE THREAD

**Issue by SSEsmaeeli** [gabrie30/ghorg#99]
I've tried to run given command but an error appears:

go get -u github.com/gabrie30/ghorg

Error is :
github.com/gabrie30/ghorg/vendor/github.com/hashicorp/go-retryablehttp
../../go/src/github.com/gabrie30/ghorg/vendor/github.com/hashicorp/go-retryablehttp/client.go:518:17: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
../../go/src/github.com/gabrie30/ghorg/vendor/github.com/hashicorp/go-retryablehttp/client.go:576:16: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
../../go/src/github.com/gabrie30/ghorg/vendor/github.com/hashicorp/go-retryablehttp/client.go:607:16: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
../../go/src/github.com/gabrie30/ghorg/vendor/github.com/hashicorp/go-retryablehttp/client.go:614:15: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)
../../go/src/github.com/gabrie30/ghorg/vendor/github.com/hashicorp/go-retryablehttp/client.go:623:14: c.HTTPClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections) github.com/gabrie30/ghorg/vendor/code.gitea.io/sdk/gitea
../../go/src/github.com/gabrie30/ghorg/vendor/code.gitea.io/sdk/gitea/client.go:139:14: undefined: http.NewRequestWithContext
../../go/src/github.com/gabrie30/ghorg/vendor/code.gitea.io/sdk/gitea/client.go:154:14: undefined: http.NewRequestWithContext

 - OS: Ubuntu 18.04

**Comment by gabrie30** [comment]
What version of go are you running? Can you go get any other repos, or is just ghorg failing? 

I was able to run a `go get -u github.com/gabrie30/ghorg` in an ubuntu image running golang1.14

**Comment by SSEsmaeeli** [comment]
Thanks for your response, I've removed old version of go and now its up to dated. but now I run `go get -u github.com/gabrie30/ghorg` nothing happen ...

**Comment by gabrie30** [comment]
Progress! Generally go will install the binary in `$HOME/go/bin`. So I'm guessing you dont have your go bin in your path. You can try adding it to your path `export PATH="$PATH:$HOME/go/bin"` then try running ghorg. Or calling it directly with `$HOME/go/bin/ghorg clone kubernetes`

If its not in your `$HOME/go/bin` for some reason you can use the find command to find out where it is `find $HOME -name ghorg`

**Comment by SSEsmaeeli** [comment]
> Progress! Generally go will install the binary in `$HOME/go/bin`. So I'm guessing you dont have your go bin in your path. You can try adding it to your path `export PATH="$PATH:$HOME/go/bin"` then try running ghorg. Or calling it directly with `$HOME/go/bin/ghorg clone kubernetes`
> 
> If its not in your `$HOME/go/bin` for some reason you can use the find command to find out where it is `find $HOME -name ghorg`

No it's installed, since `go version` give me it's current version ... 
after run `go get -u github.com/gabrie30/ghorg`, nothing will happen, after waiting a bit, terminal go to new line and allow me to run new command ... !
